### ISSUE TITLE
Does v2 conflicts with v1?

### ISSUE THREAD

**Issue by Draghmar** [emmetio/sublime-text-plugin#1]
Hi
Wanted to try this new and improved version but I couldn't find any info about installing it along with v1. Should I uninstall v1 before installing v2? I mean it seems obvious but I wanted to be sure. ;)

**Comment by sergeche** [comment]
Yes, you should uninstall (or disable) previous version

**Comment by sergeche** [comment]
Otherwise, previous version will hijack Tab key so you won’t be able to use new version

**Comment by Draghmar** [comment]
OK, thanks for clearing that up! I guess you could add this to the README just for the sake of making the obvious as clear as possible. ;)
