### ISSUE TITLE
Overrides inline comment to block comment

### ISSUE THREAD

**Issue by rchl** [emmetio/sublime-text-plugin#10]
Emmet2 is overriding inline comment action to block comment action in some syntaxes. Happens for third party `SASS` and in `Vue Component` syntaxes.

Happens for *.scss file with `Sass` syntax package installed and in *.vue files (`script` block) with `Vue component` syntax installed.

After enabling `sublime.log_commands(True)` and pressing `cmd+/` to comment out a line, Sublime prints `plugin rewritten command: emmet_toggle_comment`and creates a block comment (in `sources.scss` creates `/* */` block comment and in a vue component **script** tag creates `<!-- -->` block comment).

Emmet 0.1.6

**Comment by rchl** [comment]
I've noticed now that there is an `emmet_comment` to toggle that.
I wonder if it would be better to have it disabled by default as it's quite intrusive and not always wanted. It would be better if the user would have to assign it to the chosen key himself.
But maybe, for now, it's OK as it gets more testing.

BTW. In a vue component, script tag has these scopes:
```text.html.vue source.js.embedded.html source.js meta.export.js meta.mapping.js meta.function.js meta.block.js meta.function-call.method.js meta.group.js meta.mapping.js meta.mapping.key.js```
so the `text.html` part of the scope triggers that behavior but of course that's too lax check in that case.

**Comment by sergeche** [comment]
Yes, the goal is to check how Emmet behaves with all options enabled by default. I’m working on a UI settings & guide to walk user through all available options and enable them, if required
