### ISSUE TITLE
Tag Preview only Displays Previews of Opening Tags that Contain One or More Attributes

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#104]
https://github.com/emmetio/sublime-text-plugin#tag-preview

This is a great feature I just enabled.  I deal with many deeply-nested HTML documents.  Some elements have attributes, some do not.

Currently, this feature only shows previews for tags that have attributes.  It does not show a preview for a tag that does not have an attribute.  That would make sense if that is all this feature provided.

However, this feature also provides the ability to jump to the opening tag, but only if the opening tag has an attribute.  We should be able to jump to any opening tag regardless if it has an attribute or not.

**Comment by sergeche** [comment]
There’s Go to Tag Pair action for this
