### ISSUE TITLE
Old Liquid snippets no longer work

### ISSUE THREAD

**Issue by Jake-Seed** [emmetio/sublime-text-plugin#109]
I create Shopify themes and had created some snippets to add common liquid (Shopify's templating language) tags as abbreviations/snippets.

**ex:**

	    "config": {
	    	"markup": {
		    "snippets": {
		        "assign": "{% assign ${1:variable} = ${2:value} %}"

Originally using `assign + tab` would output `{% assign variable = value %}` with tabstops at "variable" and "value".

Now, the snippet outputs `% assign variable = value %` ignoring the curlies, though the tabstops are still correct.
I attempted to use `\\` as a character escape for the curlies, however this doesn't work, and renders the snippet completely unusable.

Things get more complex when using multi-line tags like a for loop.

Using `for>li.item + tab` with the following snippet

    "for": "{% for ${1:element} in ${2:collection} %}${newline}${indentation}${child}${newline}{% endfor %}",

my expected output is 

    {% for element in collection %}
        <li class="item"></li>
    {% endfor %}

However I am getting this

    % for element in collection %
    <1>newline</1>
    <1>indentation</1>
    <1>child</1>
    <1>newline</1>
    % endfor %<li class="item"></li>

I looked at the [snippets.json documentation](https://docs.emmet.io/customization/snippets/) for any changes, but didn't see any.

I've only recently adopted Emmet and acknowledge I could be using the snippets incorrectly, however they were working for me before the recent update. If I'm using them incorrectly, it would be great if I could get pointed in the direction of how to properly implement using curlies in a snippet. I know emmet uses curlies to indicate text, but if there is a way to escape the character, I'm unable to find it in the docs. I've tried `\\` to escape as well as using multiple curlies `{{`, but both methods break a snippet and Emmet won't recognize it.

**Comment by sergeche** [comment]
In recent update, snippets format has been changed: now snippets are aliases to another abbreviations and value inside `{...}` is a text node, which outputs contents as is. So, you have to wrap your plain snippet in another pair of `{...}` to output contents with braces. But there’s a bug in parser which prevents double braces to work properly, will be fixed soon.

Indeed, it’s not quite right way to use Emmet: it’s better to use native ST snippets for such cases, but they won’t be chainable.

**Comment by Jake-Seed** [comment]
Ah, ok. I see. I'll keep my eyes peeled for the double brace fix.

**Comment by sergeche** [comment]
Nested curly braces should be supported in v2.1.19.
Your custom snippet should look like this:

```
"for": "{{% for ${1:element} in ${2:collection} %}\n\t${child}\n{% endfor %}}",
```

Another option is to escape curly braces with `\`:

```
"for": "{\\{% for ${1:element} in ${2:collection} %\\}\n\t${child}\n\\{% endfor %\\}}",
```
