### ISSUE TITLE
Ctrl + E Binding Gone?

### ISSUE THREAD

**Issue by matthewhartman** [emmetio/sublime-text-plugin#111]
Hey There,

First off, want to thank you for your hard work on this plugin - I use it all the time and it's incredible!

I got the latest update for this plugin in Sublime and I'm noticing the Ctrl + E binding no longer works. 

Example - when I write something like this:

```js
const html = `
  div (I tab here but it doesn't work - however Ctrl + E used to expand it)
`
```

Are you able to add this binding back? or offer some sort of custom binding option?

Thanks again and looking forward to hearing back from you soon.

Cheers,

Matt

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin#all-my-keyboard-shortcuts-gonenothing-works

**Comment by matthewhartman** [comment]
Thanks Pal! 🤟

**Comment by matthewhartman** [comment]
Was hoping to pick your brains on this. But I tried the following:

`Preferences -> Package Settings -> Emmet -> Key Bindings`

Added the following code:

```
{
  "keys": ["ctrl+e"],
  "command": "emmet_expand_abbreviation"
}
```

This generated the following file `~/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap`

Restarted Sublime and CTRL+E binding is not working.

In fact when I press CTRL+E - I get the following in the bottom status bar:
`Copied find string from buffer`

**Comment by matthewhartman** [comment]
Was hoping to pick your brains on this. But I tried the following:

Preferences -> Package Settings -> Emmet -> Key Bindings

Added the following code:

{
  "keys": ["ctrl+e"],
  "command": "emmet_expand_abbreviation"
}
This generated the following file ~/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap

Restarted Sublime and CTRL+E binding is not working.

In fact when I press CTRL+E - I get the following in the bottom status bar:

![Screenshot from 2020-09-07 18-06-12](https://user-images.githubusercontent.com/1294141/92363555-ff2db380-f134-11ea-8e38-5c79dd7347ef.png)

**Comment by sergeche** [comment]
It looks like ST runs the following command, which is specified for Linux platforms:

`{ "keys": ["ctrl+e"], "command": "slurp_find_string" }`

It’s weird because key bindings in User folder should win.

Just to clear, you contents of `.sublime-keymap` should look like this:

```json
[
    {
        "keys": ["ctrl+e"],
        "command": "emmet_expand_abbreviation"
    }
]
```

**Comment by rchl** [comment]
@matthewhartman How does your `User/Default (Linux).sublime-keymap` look in full? You probably have a syntax error there. You need to put your keybinding within an array syntax (`[ { ...keybinding... } ]`).

**Comment by matthewhartman** [comment]
Ah man! I think I see the issue.

I forgot the top level array in the settings file.

I'll test it out tomorrow and get back to you. Thanks again! 🤟👌👍
