### ISSUE TITLE
Slowing down cursor movements

### ISSUE THREAD

**Issue by rchl** [emmetio/sublime-text-plugin#112]
When I press and hold arrow down or up to move the cursor quickly between the lines I see the speed being affected by emmet.

(The gifs have low framerate so it doesn't look as smooth as in reality for the "disabled" case. But you can see that the speed of movement is much higher with Emmet disabled)

Here is with emmet disabled:
![disabled](https://user-images.githubusercontent.com/153197/92282752-91984200-eefe-11ea-851e-e7f8d35947d7.gif)

Here is with emmet ENABLED:
![enabled](https://user-images.githubusercontent.com/153197/92282739-8b09ca80-eefe-11ea-82f1-a74fa01e47a4.gif)

**Comment by rchl** [comment]
I've debugged it and it's this code that causes the slowdown:

https://github.com/emmetio/sublime-text-plugin/blob/61dceeffba127ce7ab764b5f514b39cd5ec6b54b/lib/go_to_tag_pair.py#L100-L121

This file has a `source.js` and it's apparently being considered a `jsx` scope in emmet terms so this `if` is entered.

And even though this function runs in async thread, it seems to be very expensive.

**Comment by sergeche** [comment]
Will disable it in next release. I know it’s a bottleneck, especially for large HTML files, but I decided to wait for user feedback on it. The ultimate solution here is to get all tag pairs for document and cache them until document changes. So tag pairing would also work for JSX
