### ISSUE TITLE
Vue.js snippets

### ISSUE THREAD

**Issue by captain-zsa** [emmetio/sublime-text-plugin#113]
Доброго времени суток. Я работаю с vue.js и хотел бы иметь некий дефолтный шаб (как работает к примеру ! для html). Напилил примерно следующее:
`"vue": "template>div.^script+style[lang=less]"`
но данный код мне не оч нравится, так как хочется добавить в style некоторых правил сразу же, также в script запихнуть всякое типа export default и тп.

Результат кода:
```
<template>
    <div class=""></div>
</template>
<script></script>
<style lang="less"></style>
```

хотелось бы получить нечто такое:
```
<template>
    <div class="">
        
    </div>
</template>
<script>
    export default {
        // возможно сюда ещё что-то, но хотя бы так
    };
</script>
<style lang="less">
    // сюда что-то
</style>
```

Собственно, я бы рад использовать `script{}` но проблема в том, что \n там распознается как пробел, а \t игнорируется.

Прям конечно сниппет мечты - некий `vue.component`, который выдаёт подобное:
```
<template>
    <div class="component">
        
    </div>
</template>
<script>
    export default {
        name : 'Component',
    };
</script>
<style lang="less">
    .component {

    }
</style>
```
(конечно можно докрутить абсолютно всяким типа vue.component|p,d,m и всякое-всякое, но вот понять бы, как делать хотя бы простую версию, чтоб работали \n\t и тп).

Кстати, дополнительный вопрос - есть ли список допустимых символов для stylesheet сниппетов? Пока использую в начале @ но это не оч практично (к примеру scss миксины - норм подключать так, а вот less-миксины может как-то иначе было бы круто).

P.S. Да, я в курсе, что можно настроить webpack на подобные вещи, можно настроить редактор на такое, но хотелось бы всё ж работать с Emmet, если он это умеет.

**Comment by sergeche** [comment]
В новом Emmet сейчас есть баг, он неправильно обрабатывает фигурные скобки внутри текстовых узлов, чтобы можно было написать так: `script{\n\texport {...}\n}`. Но в данном случае лучше сделать нативный ST сниппет с заготовкой для Vue, новый Emmet как раз может нормально работать с наивными сниппетами.

По поводу допустимых символов в сниппетах: они могут начинаться с `@` или `$`, а также содержать только латинские символы. Числа тоже можно, но сейчас они принудительно отделяются как значение, я потом подправлю, чтобы и в названиях сниппетов можно было числа использовать

**Comment by sergeche** [comment]
В версии 2.1.19 теперь должны правильно отрабатываться вложенные фигурные скобки. Как вариант, их также можно экранировать с помощью `\`
