### ISSUE TITLE
Question for old version

### ISSUE THREAD

**Issue by Falcikas** [emmetio/sublime-text-plugin#114]
Is it possible to have separate package listed in Package Manager for V1 Emmet version ( unmaintained ) , that worked perfectly with any syntax, any file without problems for years?

**Comment by sergeche** [comment]
No. V2 also works with any syntax, anywhere. Please read README first then report issues you struggling with.

**Comment by Falcikas** [comment]
I really appreciate for the plugin - hundreds of hours saved with Emmet help. The transition to V2 is still in progress for me - for those who struggle with updated version, read this comment https://github.com/emmetio/sublime-text-plugin/issues/59#issuecomment-683747039 . Closing the issue. Thank You for doing awesome work.
