### ISSUE TITLE
The convert of the img tag does not work well.

### ISSUE THREAD

**Issue by Asterisknautz** [emmetio/sublime-text-plugin#115]
Thanks for porting the new emmet to sublime text.
I found one thing that didn't work and I hope you can fix it.

1. Prepare three image files.
```
lorem.jpg
ipsum.jpg
dolor.jpg
```

2. applied emmet(Wrap with Abberaviation).
As a result, the img tag has an unnecessary closing tag and text insertion in the img tag.
command ：` img*`

```
<img src="" alt="">lorem.jpg</img>
<img src="" alt="">ipsum.jpg</img>
<img src="" alt="">dolor.jpg</img>
```

3. This is the result of assigning the file name to the src path.
command ： `img[src="$#"]*`

```
<img src="lorem.jpg" alt="">
	lorem.jpg
	ipsum.jpg
	dolor.jpg
</img>
<img src="ipsum.jpg" alt="">
	lorem.jpg
	ipsum.jpg
	dolor.jpg
</img>
<img src="dolor.jpg" alt="">
	lorem.jpg
	ipsum.jpg
	dolor.jpg
</img>
```

4. the expected result.
command ： `img[src="$#"]* `
Execute the same command as the No3.

```
<img src="lorem.jpg" alt="">
<img src="ipsum.jpg" alt="">
<img src="dolor.jpg" alt="">
```

My English is not good, so I'm sorry if it's hard to understand.

**Comment by sergeche** [comment]
Thanks for the detailed report! Indeed, it’s a bug, will fix it soon
