### ISSUE TITLE
Wrap with Abbreviation Erratic Behavior with Trailing Space Characters

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#119]
This is an interesting issue that differs based on a single selection wrapped with [tag]* or multiple selections wrapped with just [tag].  In the examples, below, make sure to note the abbreviation used (P* or P), and single and multiple selections.

<br>Here is the "control" image.  I have three paragraphs that have no trailing space characters, as you can see from the green selection.
![wrap1a](https://user-images.githubusercontent.com/39276677/93147242-4af0d780-f6b6-11ea-9308-60eb72cd722d.png)

<br><br>I select all paragraphs with one selection region, then run the Wrap with Abbreviation command.   The result is nicely formatted as expected.
![wrap1b](https://user-images.githubusercontent.com/39276677/93147329-85f30b00-f6b6-11ea-8c67-350dd3af2568.png)

<br><br>Now, to demonstrate the issue, I added one trailing space character at the end of each line.
![wrap2a](https://user-images.githubusercontent.com/39276677/93147356-986d4480-f6b6-11ea-854e-e01ba0eac304.png)

<br><br>Again, I select all paragraphs with one selection region, then run the Wrap with Abbreviation command.  This time, the second and third paragraphs are prefixed with a space character and indented.  This is not expected. Also, note that the trailing space character precedes the ending P tag, as expected.
![wrap2b](https://user-images.githubusercontent.com/39276677/93147399-ac18ab00-f6b6-11ea-9eee-5731c362b472.png)

<br><br>To demonstrate the second part of this issue, I add multiple spaces to the end of the first and second paragraphs.  (The number of space characters is not important.)  Notice that I have three selection regions; one for each paragraph including any trailing spaces.
![wrap3a](https://user-images.githubusercontent.com/39276677/93147419-bcc92100-f6b6-11ea-8918-d098495a8152.png)

<br><br>When I wrap the three selection regions with the P tag, the trailing spaces are placed _outside_ the closing P tag.  The lines are not indented.
![wrap3b](https://user-images.githubusercontent.com/39276677/93147428-c3579880-f6b6-11ea-94c8-ec5e88c43e65.png)

In addition to resolving these two issues, if I had my choice on how I would like this to operate, I would prefer that Wrap with Abbreviation trims all leading and trailing space characters.  I can't imagine the need to have a space character directly after an opening tag or directly before a closing tag.  Perhaps this could be an option to enable or disable.

Thank you for looking at this issue.

**Comment by sergeche** [comment]
Thanks for detailed report, will look into it. Yes, Emmet currently narrows selection to non-space characters, it does so to properly wrap contents of tag when there's no selection at all. I guess I shouldn't narrow to non-space when there's user selection

**Comment by michaelalandawson** [comment]
Thank you.  Can you have a setting so that it eliminates leading and trailing space characters?

**Comment by michaelalandawson** [comment]
Thank you!  This is very helpful.
