### ISSUE TITLE
⋮> Contrast Could be Improved

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#120]
Can you increase the contrast of the ⋮> characters, please?  Or, can you give it a scope that we can use our own color settings?

![117](https://user-images.githubusercontent.com/39276677/93395318-4e619b80-f83b-11ea-9714-01b2812780c2.png)

Thanks!

**Comment by sergeche** [comment]
You can add custom CSS with `popup_css` Emmet config option. You can write something like `.indicator { color: black }`
