### ISSUE TITLE
Very simple test does not work

### ISSUE THREAD

**Issue by Mandras** [emmetio/sublime-text-plugin#123]
This test does not work for me, on ST3: `ul>li.test`

It result to:

`ul><li class="test"></li>`

**Comment by sergeche** [comment]
Did you set document syntax to HTML? Also, check ST console for errors

**Comment by Mandras** [comment]
I've checked again and it seems to work
I think I was on a .php file
If the bug happend again I will check console

**Comment by sergeche** [comment]
Closing for now, please create new issue if you still experience problems
