### ISSUE TITLE
Some old abbreviations not working in sublime

### ISSUE THREAD

**Issue by tijosfx** [emmetio/sublime-text-plugin#125]
Hi,
-bdrs or -bxs or any webkit abbreviations not working in sublime, Help me, please

or what is the abbreviation for below css?

-webkit-border-radius: ;
-moz-border-radius: ;
-ms-border-radius: ;
-o-border-radius: ;
-----or----
display: -webkit-flex; 
display: -moz-flex; 
display: -ms-flex; 
display: -o-flex; 
display: flex;

Thanks
Tijo

**Comment by sergeche** [comment]
Vendor prefixes are outdated and not supported anymore, use tools like PostCSS instead
