### ISSUE TITLE
explicit abbreviation mode still has problem.

### ISSUE THREAD

**Issue by MOONLIGHTV** [emmetio/sublime-text-plugin#126]
### **using explicit abbreviation mode with "auto_mark": false**

- has captured underline

- has  ⋮> mark

- not show the preview
![93285107-a9c56680-f806-11ea-8abd-9b716a1d4547](https://user-images.githubusercontent.com/14039419/93694701-8cafd100-fb41-11ea-9fe1-5d2d8200c7f6.gif)
**It's not only me has this problem, other guy tried it and he can reappear it too.**

In your README document：https://github.com/emmetio/sublime-text-plugin#disable-abbreviation-capturing
You can let the preview work with abbreviation capturing disabled, I don't know how?
![emmet6](https://user-images.githubusercontent.com/14039419/93694805-a6054d00-fb42-11ea-8cfa-d7bd15614fc4.gif)

**Comment by sergeche** [comment]
Just to be clear: you've disabled auto_mark and don't see previews in abbreviation mode? That's definitely a bug

**Comment by sergeche** [comment]
Fixed in v2.1.20

**Comment by MOONLIGHTV** [comment]
> Just to be clear: you've disabled auto_mark and don't see previews in abbreviation mode? That's definitely a bug

Yes, that's it.
