### ISSUE TITLE
Preview Popup Flickers when Typing Abbreviation

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#127]
ST3 3211, Emmet 2.1.20

When typing an abbreviation, it can be anything, the popup preview window flickers with every keystroke.  When the preview flickers, you can briefly see the code directly behind the preview popup.

auto_mark is "true".

**Comment by sergeche** [comment]
It's a known issue of ST3, fixed in ST4

**Comment by michaelalandawson** [comment]
Thank you.
