### ISSUE TITLE
安装报错啊

### ISSUE THREAD

**Issue by ly-wrzz** [emmetio/sublime-text-plugin#128]
安装第一个没问题吧？
![image](https://user-images.githubusercontent.com/44197398/93838893-c86fa580-fcbd-11ea-93c6-99e910399b30.png)
直接报错！
![image](https://user-images.githubusercontent.com/44197398/93838941-e5a47400-fcbd-11ea-9d02-7c10a13fd68d.png)

**Comment by MOONLIGHTV** [comment]
> 安装第一个没问题吧？
> ![image](https://user-images.githubusercontent.com/44197398/93838893-c86fa580-fcbd-11ea-93c6-99e910399b30.png)
> 直接报错！
> ![image](https://user-images.githubusercontent.com/44197398/93838941-e5a47400-fcbd-11ea-9d02-7c10a13fd68d.png)

要翻墙的

**Comment by ly-wrzz** [comment]
好的谢谢，你有好用的翻墙工具没，求推荐

**Comment by princemaple** [comment]
Note to maintainer: It's caused by China GFW.
