### ISSUE TITLE
Numbering Items in reverse starts at 2

### ISSUE THREAD

**Issue by vicgonvt** [emmetio/sublime-text-plugin#13]
When expanding the following 

`ul>li.item$@-*5`

this results in 

```html
<ul>
	<li class="item6"></li>
	<li class="item5"></li>
	<li class="item4"></li>
	<li class="item3"></li>
	<li class="item2"></li>
</ul>
```

With the expected result to be

```html
<ul>
	<li class="item5"></li>
	<li class="item4"></li>
	<li class="item3"></li>
	<li class="item2"></li>
	<li class="item1"></li>
</ul>
```

Screenshot from Sublime Text 3.2.2 build 3211 & 

![Screen Shot 2020-01-05 at 12 16 29 PM](https://user-images.githubusercontent.com/7350307/71783544-2c2e3300-2fb6-11ea-865f-37939bb77cd4.png)

**Comment by sergeche** [comment]
Fixed in v0.1.8
