### ISSUE TITLE
Parent>{TEXT} not working

### ISSUE THREAD

**Issue by jw2090** [emmetio/sublime-text-plugin#130]
I'm having an issue in Sublime Text 3 where Emmet seems to fail. Here's the code I'm trying to use:

p>{Click }+a{here}+{ to continue}

When I enter 'Emmit Abbreviation Mode' the green :> disappears as soon as I try to add text to the parent element. The curly brace after: p> stops the process.

**Comment by sergeche** [comment]
Found a bug in plugin, will fix it soon
