### ISSUE TITLE
Native Lazy Loading

### ISSUE THREAD

**Issue by ahmetcadirci25** [emmetio/sublime-text-plugin#132]
Is it possible to add lazy code?

```
img:lazy, img:l

<img loading="lazy" src="" alt="" />
```

```

iframe:lazy, ifr:l,

<iframe src="" loading="lazy" frameborder="0"></iframe>
```

**Note:** 

> lazy: is a good candidate for lazy loading.
> eager: is not a good candidate for lazy loading. Load right away.
> auto: browser will determine whether or not to lazily load.

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets
