### ISSUE TITLE
emmet_wrap_with_abbreviation: weird behavior

### ISSUE THREAD

**Issue by freder** [emmetio/sublime-text-plugin#134]
after upadting to the latest version, I re-enabled the shortcut for `emmet_wrap_with_abbreviation ` (= `ctrl+w`), but it shows some weird behavior. invoking it from the command palette works just fine though:

![emmet-wrap](https://user-images.githubusercontent.com/724844/95615890-3e6b5f00-0a69-11eb-86a8-2061309cb39e.gif)

at first I thought the key binding might be conflicting with s.th. else, but there is nothing else bound to `ctrl+w` in my config.

**Comment by sergeche** [comment]
Can’t reproduce. Do you see any errors in ST console? Also, you can run `sublime.log_commands(True)` in console and check which commands are invoked when you run this action

**Comment by freder** [comment]
in `plain text` mode:

```
DEBUG - storing :history: [('insert', {'characters': 'test'})]
DEBUG - setting window setting ':history:' to '[('insert', {'characters': 'test'})]'
DEBUG - storing :history: [('move_to', {'extend': True, 'to': 'bol'}), ('emmet_wrap_with_abbreviation_preview', {'items': [[0, 4, '<asdf>test</asdf>']]})]
DEBUG - setting window setting ':history:' to '[('move_to', {'extend': True, 'to': 'bol'}), ('emmet_wrap_with_abbreviation_preview', {'items': [[0, 4, '<asdf>test</asdf>']]})]'
SublimeLinter: sublime_linter.py:345  Delay linting '<untitled 209>' for 0.1s
INFO - Delay linting '<untitled 209>' for 0.1s
SublimeLinter: sublime_linter.py:361  No installed linter matches the view.
INFO - No installed linter matches the view.
SublimeLinter: sublime_linter.py:345  Delay linting '<untitled 209>' for 0.1s
INFO - Delay linting '<untitled 209>' for 0.1s
SublimeLinter: sublime_linter.py:345  Delay linting '<untitled 209>' for 0.1s
INFO - Delay linting '<untitled 209>' for 0.1s
SublimeLinter: sublime_linter.py:345  Delay linting '<untitled 209>' for 0.1s
INFO - Delay linting '<untitled 209>' for 0.1s
SublimeLinter: sublime_linter.py:345  Delay linting '<untitled 209>' for 0.1s
INFO - Delay linting '<untitled 209>' for 0.1s
SublimeLinter: sublime_linter.py:361  No installed linter matches the view.
INFO - No installed linter matches the view.
SublimeLinter: sublime_linter.py:345  Delay linting '<untitled 209>' for 0.1s
INFO - Delay linting '<untitled 209>' for 0.1s
SublimeLinter: sublime_linter.py:361  No installed linter matches the view.
INFO - No installed linter matches the view.
DEBUG - storing :history: [('emmet_wrap_with_abbreviation', {'wrap_abbreviation': 'asdf'})]
DEBUG - setting window setting ':history:' to '[('emmet_wrap_with_abbreviation', {'wrap_abbreviation': 'asdf'})]'
```

---

disabling all plugins except `Emmet` makes it work. – enabling `SublimeLinter` breaks it, so it must have s.th. to do with that.
I will investigate further...

**Comment by freder** [comment]
**update:**

it has nothing do with how the command is invoked.

I was able to narrow it down to the following:

![emmet](https://user-images.githubusercontent.com/724844/97079576-7a6bfb80-15f5-11eb-918c-e73764b2b842.gif)

- the first time the command is invoked it works
- on the second time the input field remembers the last abbreviation entered. even when clearing the input field, the selected text will still be wrapped in the old tag (`<code>`)
    - when hitting enter, the 4 characters it thinks are `test` are replaced with `<li>test</li>` – and that how we end up with `<li>test</li>e>test</code>`

**Comment by sergeche** [comment]
Still can’t reproduce it. Trying to repeat the same actions as you do in GIF, but it works fine. Which Emmet version you have installed?

**Comment by freder** [comment]
- sublime text 3.2.2
- emmet 2.1.22

**Comment by freder** [comment]
update: I have figured it out -- somehow https://github.com/guillermooo/Six was the culprit.
