### ISSUE TITLE
Problem about the Tab key.

### ISSUE THREAD

**Issue by MOONLIGHTV** [emmetio/sublime-text-plugin#135]
I use the Tab to expand emmet code.
I also use the Tab key to expand my js code as the image shows:
![3](https://user-images.githubusercontent.com/14039419/96157183-8d6f3380-0f44-11eb-96e2-eb5898344a73.gif)
**it works fine in emmet version 1.**

**emmet version 2.**
**I know the it's default use Tab to expand in capturing mode,
but I don't want to use capturing:**
`"auto_mark": false,`
So I need add this settings:
`    {
        "keys": ["tab"],
        "command": "emmet_expand_abbreviation"
    },`
tab just broken when I using it to expand my js code like this:
![2](https://user-images.githubusercontent.com/14039419/96157193-92cc7e00-0f44-11eb-9e35-3dc93503bc6a.gif)
the same result in HTML file or Javascript file.

**Is there any way to fix it?** 
**I don't want to use enter/ctrl+e or any other key for alternative key to Tab.**

**Comment by sergeche** [comment]
The reason for abbreviation capturing is to behave exactly as you need: capture abbreviations in valid contexts only and Tab to expand it or Esc then Tab to expand native ST snippet.

Why did you disable abbreviation capturing?

**Comment by MOONLIGHTV** [comment]
> The reason for abbreviation capturing is to behave exactly as you need: capture abbreviations in valid contexts only and Tab to expand it or Esc then Tab to expand native ST snippet.
> 
> Why did you disable abbreviation capturing?

Because capurting is diffcult to use.
If you write a wrong comma, yes, you can use arrow key to come back capurting.
But if you accidentally press backspace twice, you can't come back any more, you have to rewrite the letter which you deleted before, then the capturing underling come back.
![1](https://user-images.githubusercontent.com/14039419/96162340-ffe31200-0f4a-11eb-86d5-762717cdf42a.gif)

Use arrow keys move again and again to find the underling, that's too troublesome for me. 
Disable caputring I only need press Tab to expand like how emmet version 1 works, simple and quick.

**Comment by sergeche** [comment]
Which version of Emmet plugin you have? This issue was fixes a while ago

**Comment by MOONLIGHTV** [comment]
> Which version of Emmet plugin you have? This issue was fixes a while ago

![无标题](https://user-images.githubusercontent.com/14039419/96206684-0cdc2180-0f9c-11eb-9d64-1c8c0400f13f.png)

**Comment by sergeche** [comment]
Most recent version is 2.1.22

**Comment by sergeche** [comment]
Does it work for you in latest Emmet version?
