### ISSUE TITLE
Expand abbreviation doesn't work

### ISSUE THREAD

**Issue by dmytrohavrysh** [emmetio/sublime-text-plugin#137]
Hi!
When i try to expand abbreviation with the help of an Emmet
`(tr>td{$}*5)*7`
it doesn't work.
![Emmet](https://user-images.githubusercontent.com/32480992/96608824-80ff2800-1302-11eb-909a-4cad28abab27.gif)

**Comment by TheDoctorWhoo** [comment]
Use Ctrl+Space instead of Tab, or use this: https://github.com/emmetio/sublime-text-plugin#i-dont-like-new-behavior-with-abbreviation-capturing-id-like-to-expand-with-tab-as-earlier

**Comment by sergeche** [comment]
@dmytrohavrysh looks like a bug, will take a look

**Comment by sergeche** [comment]
Fixed in v2.2.1
