### ISSUE TITLE
Closing comments not working

### ISSUE THREAD

**Issue by PUShAUNE** [emmetio/sublime-text-plugin#142]
Hi,

With the latest updates, the closing comments went down.
I use this preference to add them when I hit the TAB button:

```
"preferences":
	{
		"filter.commentAfter": "<!-- /<%= attr(\"id\", \"#\") %><%= attr(\"class\", \".\") %> -->"
	},
	"syntaxProfiles":
	{
		"html":
		{
			"filters": "html, c"
		}
	},
}
```

Any idea why it is not working?

**Comment by sergeche** [comment]
Emmet config has been changed, refer to Emmet.sublime-settings file for more info
