### ISSUE TITLE
Trouble with single line css

### ISSUE THREAD

**Issue by charroma** [emmetio/sublime-text-plugin#144]
The css autocomplete is having trouble when you write css on a single line.
If it's a new rule, it only works when I enter the css on a new line.
<img width="153" alt="Screen Shot 2020-12-04 at 15 58 06" src="https://user-images.githubusercontent.com/65042439/101214222-a72a1e80-3649-11eb-9e7f-59017de26906.png">
<img width="163" alt="Screen Shot 2020-12-04 at 15 58 21" src="https://user-images.githubusercontent.com/65042439/101214231-abeed280-3649-11eb-96d1-114f9dc8b6c6.png">

If css is already present on the line, it only works if I add the css at the beginning of the rule or if I add a new line
<img width="222" alt="Screen Shot 2020-12-04 at 15 55 50" src="https://user-images.githubusercontent.com/65042439/101214282-c7f27400-3649-11eb-82db-8aa2dd4c96ea.png">
<img width="334" alt="Screen Shot 2020-12-04 at 15 56 04" src="https://user-images.githubusercontent.com/65042439/101214297-cd4fbe80-3649-11eb-9f5f-af8ca7a71fe4.png">
<img width="177" alt="Screen Shot 2020-12-04 at 15 56 37" src="https://user-images.githubusercontent.com/65042439/101214321-d9d41700-3649-11eb-9932-a404bdeef524.png">

**Comment by sergeche** [comment]
Should be fixed in v.2.3.1

**Comment by charroma** [comment]
It's now working. Thanks.
