### ISSUE TITLE
Mixed-case Email Addresses Ignored by Wrap with Abbreviation

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#145]
It appears that Emmet's Wrap with Abbreviation command ignores any email addresses that have upper-case letters anywhere in the address.

Wrap each example with 'a' tag:

`user@mylongdomainname.com`
Result: href attribute populated as expected
`<a href="mailto:user@mylongdomainname.com">user@mylongdomainname.com</a>`

`user@myLongDomainName.com`
Result: href attribute not populated
`<a href="">user@myLongDomainName.com</a>`

`uSEr@mylongdomainname.com`
Result: href attribute not populated
`<a href="">uSEr@mylongdomainname.com</a>`

Thanks!

**Comment by sergeche** [comment]
Should be fixed in v2.3.2

**Comment by michaelalandawson** [comment]
Thank you!

**Comment by michaelalandawson** [comment]
Fix confirmed.
