### ISSUE TITLE
Feature XHTML/self_closing_tag stopped working

### ISSUE THREAD

**Issue by fuweichin** [emmetio/sublime-text-plugin#147]
I used to configure Sublime Text Emmet 'Expand HTML tag as XHTML', but it now days it suddenly stopped working.
I checked my `User/Emmet.sublime-settings` (part of its options was coppied from `Emmet/Emmet.sublime-settings`)

```json
{
	"syntaxProfiles": {
		"html": "xhtml"
	},
	"telemetry": true,
	"uid": "0c743ba0-1e6c-4fc7-a485-657edadadb59"
}
```

I tried to borrow  emmet config from `.vscode/settings.json` which is working in VSCode

```json
{
   "emmet.syntaxProfiles": {
        "html": {
            "self_closing_tag": "xhtml"
        }
    }
}
```

so User/Emmet.sublime-settings bacame

```json
{
  "syntaxProfiles": {
    "html": {
      "self_closing_tag": "xhtml"
    }
  }
}
```

not working

I tried reinstalling Emmet for Sublime Text, still not working. (`Emmet/Emmet.sublime-settings` gets updated during the reinstallation, not a "syntaxProfiles" thereafter)

So any migration guide to the issue?

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L151
