### ISSUE TITLE
Do we  have `includeLanguages`? 

### ISSUE THREAD

**Issue by Afrowave** [emmetio/sublime-text-plugin#150]
I am testing out React on VSCode and there are is the `includeLanguages` setting that I looked for in ST and I can't find it.

What needs to be done to make it work? It really makes VSCode shine in this area.

**Comment by sergeche** [comment]
What this option should do and which options you've tried in ST?

**Comment by Afrowave** [comment]
Hey @sergeche,

this option is meant to allow a user to include languages where Emmet should look for HTML or CSS like code within the source file.

For example:

![Screenshot 2020-12-25 at 20 26 45](https://user-images.githubusercontent.com/271274/103139669-92442680-46ef-11eb-8c9a-d14b23dfeab6.png)


This is a `javascriptreact` file using the CSS-in-JS design feature≥. This is activated in the emmet settings in VSCode under `includeLanguages` where a user adds `javascriptreact` to active Emmet in React JS files.

I have added the option:
```
{
	"js_prefix": true,
}
```
I am getting `<tag></tag>` completion, but not the emmet abbreviation options like in the picture above.

**Comment by sergeche** [comment]
Did you checked Emmet preferences file?

https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L29

**Comment by Afrowave** [comment]
Yes, I did. There is no `js`in the `syntax_scopes`. But now that you ask, I have added the options:
```
{
	"js_prefix": true,
	"syntax_scopes": {
		"js": "source.js",
	}
}
```
It looks like it is working now.

![Screenshot 2020-12-25 at 21 01 01](https://user-images.githubusercontent.com/271274/103140167-860e9800-46f4-11eb-987d-d09c67de101f.png)
