### ISSUE TITLE
Unable to download Emmet

### ISSUE THREAD

**Issue by hjijin** [emmetio/sublime-text-plugin#152]
when i use Package Contro to install Emmet, error like this: 

`Unable to download Emmet. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Emmet", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Error downloading package. curl: (7) Failed to connect to emmetio.github.io port 443: Connection refused downloading https://emmetio.github.io/sublime-text-plugin/2.3.2/Emmet.sublime-package.
error: Package Control`

but install others are ok, maybe the problem is the site:  emmetio.github.io, 404.

**Comment by sergeche** [comment]
Check if https://emmetio.github.io/sublime-text-plugin/2.3.2/Emmet.sublime-package works for you, seems like a local problem, not related to Emmet itself

**Comment by hjijin** [comment]
> Check if https://emmetio.github.io/sublime-text-plugin/2.3.2/Emmet.sublime-package works for you, seems like a local problem, not related to Emmet itself

OK, thanks.
