### ISSUE TITLE
Emmet not expanding in JS files but works with html

### ISSUE THREAD

**Issue by JamesDullaghan** [emmetio/sublime-text-plugin#154]
I've recently done a fresh install of emmet and sublime text on 2 different computers and for whatever reason neither seem to be expanding on either inside of JS files but do expand inside of html files. 

Any idea what this could be caused by? There are no errors in the sublime text console and there are no issues with the plugin. The only modification made is adding:

```json
[
 {
    "keys": ["ctrl+e"],
    "command": "emmet_expand_abbreviation"
  }
]
```

**Comment by sergeche** [comment]
You can open ST console, run `sublime.log_commands(True)` and then check which command is invoked via `ctrl-e` shortcut. You may have another command bound to this shortcut in HTML
