### ISSUE TITLE
CSS completions clash with CSS3 package

### ISSUE THREAD

**Issue by ryboe** [emmetio/sublime-text-plugin#157]
It used to be possible to disable Emmet's CSS completions with this setting.

```yaml
"show_css_completions": false
```

That setting has been removed from Emmet 2 AFAICT. Is it possible to disable CSS completions in the new version of Emmet?

I'm the maintainer of [CSS3](https://packagecontrol.io/packages/CSS3), which is the 44th most installed Sublime plugin. CSS3's completions clash with Emmet's to the point that the packages can't both be enabled at the same time in CSS files. I've been directing my users to set `show_css_completions: false` for a long time, but that no longer works. Do you have any suggestions about how our packages can better coexist? Thanks!

**Comment by sergeche** [comment]
There’s a number of ways to disable abbreviations: https://github.com/emmetio/sublime-text-plugin#disable-abbreviation-capturing

**Comment by sergeche** [comment]
Basically, Emmet now acts as autocomplete provider so it can better integrate with ST and other packages. There’s a complete description of how CSS support works in Emmet and how it can be tuned for better experience: https://github.com/emmetio/sublime-text-plugin#css-support

**Comment by ryboe** [comment]
Thank you for the info! If I understand correctly, I should direct my users to set `"abbreviation_preview": "markup"` to disable completions for CSS only. Is that correct?
