### ISSUE TITLE
Elements with Self-closing tags

### ISSUE THREAD

**Issue by NicholasJohn16** [emmetio/sublime-text-plugin#159]
Is there a way to generate elements with self closing tags? For instance, expand `<Player/` into `<Player/>` instead of `<Player></Player>`.

**Comment by sergeche** [comment]
You can add slash at the end of element, e.g. `Player/`

**Comment by NicholasJohn16** [comment]
I've tried that, but it doesn't seem to work. It just completes to `<Player>`.

**Comment by sergeche** [comment]
Check out this preference: https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L151
