### ISSUE TITLE
The right filename/path for user preferences?

### ISSUE THREAD

**Issue by certainlyakey** [emmetio/sublime-text-plugin#16]
What is the right location for a custom user preferences file? 

Usually it's `User/{Package name}.sublime-settings`, but for me settings set neither in `Emmet2.sublime-settings` nor in `Emmet.sublime-settings` don't seem to work.

Also (related to #11) in v0.1.8, when you open the Preferences → Package Settings → Emmet2 → Settings menu item, in the right pane Sublime Text general prefs are opened. Expectation (at least this happens with other packages) is that in the right pane we have an Emmet2 own user settings file opened.

**Comment by sergeche** [comment]
Emmet settings are added into default editor preferences. All available options are described in https://github.com/emmetio/sublime-text-plugin/blob/master/Preferences.sublime-settings

**Comment by certainlyakey** [comment]
Why so? Doesn't seem to be the conventional way.

**Comment by sergeche** [comment]
Will think about it. I had some issues with custom package file, may try it again sometimes

**Comment by certainlyakey** [comment]
Cool, thanks!
