### ISSUE TITLE
Snippet not working after expansion

### ISSUE THREAD

**Issue by paulmist** [emmetio/sublime-text-plugin#162]
I've had this issue repeatedly, usually expanding `php` + tab as a snippet.

The expected result should be `<?php ?>` however, when doing this directly after an abbreviation has been expanded it simply jumps the cursor to the end of the previous tags.

![screencast 2021-04-21 09-33-08](https://user-images.githubusercontent.com/796792/115524006-92ab9300-a285-11eb-8b82-49caccb3d698.gif)

Package, Sublime and OS (macOS) fully updated.

**Comment by sergeche** [comment]
It’s a default behaviour of ST tabstops: you should reset it first with Esc key

**Comment by paulmist** [comment]
Understood - thanks for explaining.
