### ISSUE TITLE
Change from double quotes to single quotes

### ISSUE THREAD

**Issue by ozgrozer** [emmetio/sublime-text-plugin#163]
Even though I have this setting in my `Emmet.sublime-settings` file, it still adds double quotes when I press the tab key. I think something broke in one of the last updates but I'm not sure.

Is there any workaround to fix this?

```json
{
  "syntaxProfiles": {
    "jsx": {
      "attr_quotes": "single",
      "self_closing_tag": true
    }
  }
}
```

**Comment by sergeche** [comment]
Config format has been changed: https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets

It should be something like this:

```json
{
    "config": {
        "jsx": {
            // https://github.com/emmetio/emmet/blob/master/src/config.ts#L110
            "options": {
                "output.attributeQuotes": "single"
            }
        }
}
```

**Comment by ozgrozer** [comment]
I didn't know about that. All of my research was leading me to the same answer, the one in my previous message. But thank you, it's working now.

**Comment by cochinet** [comment]
Hi there, I'm missing something here and I'm having a hard time trying to figure this out. Maybe you guys can help me :)

I had this in my syntaxProfiles.json

```
{
    // force XHTML profile for HTML syntax
    "html": "xhtml",

    // create our own profile for XML
    "xml": {
    	"filters": "html, ctp",
        "tag_case": "upper",
        "attr_quotes": "single"
    }
}
```

Can't figure out how to upgrade it to the new config structure. 

Thanks 👍

**Comment by sergeche** [comment]
@cochinet my answer above shows sample config for single quotes

**Comment by cochinet** [comment]
@sergeche Sure, thanks, I got that working, the thing that I'm having trouble with is making that configuration work with `ctp`files. Any help would be very appreciated. Thanks.
