### ISSUE TITLE
strange autocomplete in sss files

### ISSUE THREAD

**Issue by isour** [emmetio/sublime-text-plugin#17]
In sss files, if i type : 
`p0` and press TAB
i result this: `padding: 0;`
if i type `m0` and press TAB i result this `m0	`
if i type `p0+m0` and press TAB i result `margin: 0;
padding: 0;`

why `m0` works like that?

**Comment by sergeche** [comment]
Works fine for me. Which plugin do you use for SugarSS highlighting?
