### ISSUE TITLE
Missing semicolon in expanded values in CSS in @media

### ISSUE THREAD

**Issue by kubiqsk** [emmetio/sublime-text-plugin#173]
(*I'll use this | as a cursor position)

### Missing semicolon in expanded values in CSS in @media

It works for code like
```
#test{
    db|
}
```
it becomes
```
#test{
    display: block;
}
```

but when you're inside @media, then

```
@media (max-width: 767px){
    #test{
        db|
    }
}
```

becomes

```
@media (max-width: 767px){
    #test{
        display: block
    }
}
```

Missing semicolon means inconsistent behavior and it becomes even worse, when you want to use more attributes like `m0+p0` - then there are missing semicolons everywhere

That the really big problem, because then it's completely invalid CSS

**Comment by MelkonSimonyan** [comment]
I have this problem too.
Missing semicolon in media queries.

**Comment by paulmist** [comment]
This issue still persists.
Is the repo still active?

**Comment by paulmist** [comment]
Awesome.

Let me know if I can do/provide anything to help the debug.

**Comment by paulmist** [comment]
Any luck finding the cause?

**Comment by sergeche** [comment]
Working on it, please ping me again at the end of the week, been very busy last few month

**Comment by paulmist** [comment]
No problem! Appreciate the work.

**Comment by paulmist** [comment]
> Working on it, please ping me again at the end of the week, been very busy last few months

Ping!

**Comment by sergeche** [comment]
Just released v.2.4.0 with fix, please check it out

**Comment by paulmist** [comment]
Checked and confirm it's working. Thank you.
