### ISSUE TITLE
Not working after update 2.4

### ISSUE THREAD

**Issue by Ilyaszhumataev** [emmetio/sublime-text-plugin#181]
Not working after update 2.4
In css file... in @media query not working emmet
Example 
@media (max-widht:1200px) {
.example_class {
here not working emmet
}
}

**Comment by sergeche** [comment]
What's your ST version?

**Comment by Ilyaszhumataev** [comment]
st 4
My list package https://ibb.co/HG4QZbQ https://ibb.co/KzNT8dp
If open css file as scss...emmet working good... in view -> syntax I open css file as scss ... but if open css file as css in @media query emmet not working

**Comment by sergeche** [comment]
What’s your full ST build version (e.g. 4143)?

**Comment by sergeche** [comment]
Works fine in latest build

<img width="256" alt="image" src="https://user-images.githubusercontent.com/93595/213642103-379e2861-0d30-4587-910b-b329353380a5.png">

**Comment by Ilyaszhumataev** [comment]
https://ibb.co/KxspYdy

**Comment by Ilyaszhumataev** [comment]
Works fine... thanks!
