### ISSUE TITLE
Enable Emmet in Elixir's EEx and HEEx templates

### ISSUE THREAD

**Issue by distefam** [emmetio/sublime-text-plugin#184]
Would it be possible to add support for Elixir files with embedded HTML? They are [supported in VSCode](https://pragmaticstudio.com/tutorials/formatting-heex-templates-in-vscode) using Emmet so it should be possible I think.

**Comment by sergeche** [comment]
I think you can add support via preferences by passing proper scope selectors for your syntax.
You should check [`syntax_scopes`](https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L29) and [`abbreviation_scopes`](https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L54)
