### ISSUE TITLE
Add autocompletion for custom source

### ISSUE THREAD

**Issue by dylanfisher** [emmetio/sublime-text-plugin#188]
Hi, thanks for your work on this plugin, and apologies if this has already been brought up in another issue or documentation. I tried to research how to enable this functionality, but was unable to figure it out. 

I want to enable emmet tab completion for `.astro` files (https://astro.build/) in the same way `.html` files are handled.

How would I configure emmet to register this source as a html scope?

![Screenshot 2024-08-18 at 9 58 53 AM](https://github.com/user-attachments/assets/45f7d73e-e93e-4ce7-97ae-fcfef233cb96)

**Comment by sergeche** [comment]
You need to open Emmet preferences and update [`syntax_scopes.html`](https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L30) to make Emmet understand that given syntax should be treated as HTML, and add/update [`abbreviation_scopes`](https://github.com/emmetio/sublime-text-plugin/blob/master/Emmet.sublime-settings#L55) so plugin can understand where to activate abbreviation
