### ISSUE TITLE
Implement RenameTag

### ISSUE THREAD

**Issue by TheSecEng** [emmetio/sublime-text-plugin#24]
Emmet2 is missing the RenameTag functionality

**Comment by ulfgj** [comment]
yup. as a sample, my sublime setting doesn't work any more.
```
 // emmet rename tag
    {
        "keys": ["super+;"], "command": "rename_tag",
        "context": [
            {
                "key": "emmet_action_enabled.rename_tag"
            }
        ]
    },
```

**Comment by BirdyOz** [comment]
Yes please.   I used this constantly and it is sorely missed.  I have tried to achieve the same by chaining multiple emmet actions together, but this is not working (or my brain is not working)

**Comment by ulfgj** [comment]
@BirdyOz agree. using it all the time!
quick workaround:
```<h2>blablabal</h2>```

select the `h2>` part and press `cmd+d` or `ctrl+d` to select the closing tag

**Comment by sergeche** [comment]
Yes, will implement that action soon

**Comment by ulfgj** [comment]
(thnx @sergeche for your work!)

**Comment by alangistfluff** [comment]
+1

I installed Emmet JUST for this functionality and **really** miss it :'(

Thank you so much for making ST support this, with Emmet. Sorry I don't use Emmet more : /

**Comment by sergeche** [comment]
Added Rename Tag in v2.1.14. Note that it also has no default key binding, but you can add is as described here: https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by ulfgj** [comment]
awesome! how long will it take before sublime automatically updates the package though package manager?

**Comment by Darkside73** [comment]
Just restart ST and it will fetch packages fresh versions

**Comment by Darkside73** [comment]
@sergeche Thanks for quick fix.
Here is my key bindings for new Emmet version: https://gist.github.com/Darkside73/d69fc2e8e5b1598fb026b5979f9267fb

**Comment by ulfgj** [comment]
> Just restart ST and it will fetch packages fresh versions

did it 5 times before it worked :D
