### ISSUE TITLE
Telemetry has to be opt-in per Package Control conventions

### ISSUE THREAD

**Issue by FichteFoll** [emmetio/sublime-text-plugin#34]
Per our conventions after the SideBarEnhancements incident with kite, we decided to require any sort of telemetry or other forms of collecting usage data to be opt-in. The recent changes in https://github.com/emmetio/sublime-text-plugin/commit/52571eeb60c90319b999e93993be807f02408159 do not follow this. I know we don't document this well, but that is why I'm creating this issue to make you aware of it.

**Please address this ASAP, otherwise your package will be purged from the default channel.**

Please see https://forum.sublimetext.com/t/rfc-default-package-control-channel-and-package-telemetry/30157 for details.

**Comment by FichteFoll** [comment]
By the way, you never persisted the setting change you do with `sublime.save_settings`, so a user will receive a new uid on every ST start. 

Regarding the online configuration thing, as per the comment in the settings file, you will have to inform the user about how you "track" them in a way that they have to be aware of it, either through an ok_cancel dialog or by asking them to put their uid token in the settings, which I personally consider to be enough user action to trigger their awareness. 

Note that there doesn't seem to be any authentication and tokens are just uuid4s, so either the configuration must be read-only or you risk manipulation of a user's settings by a malicious party.

If you have any further question, don't hesitate to direct them at me.

**Comment by sergeche** [comment]
OK, thanks for pointing me out about `save_settings()`. I’ve disabled telemetry by default for now, I’ll add confirm dialog later. 

> Note that there doesn't seem to be any authentication and tokens are just uuid4s, so either the configuration must be read-only or you risk manipulation of a user's settings by a malicious party.

Yes, it’s just a read-only token. I’m experimenting with online config for Emmet so I need an easy way to identify editor instance. Right now, I’m just collecting data about how users interact with Emmet so I can better understand which parts should be improved.

PS: Kite also wanted to purchase Emmet back then :)
