### ISSUE TITLE
Non-plugin python modules should be moved to a subdirectory

### ISSUE THREAD

**Issue by deathaxe** [emmetio/sublime-text-plugin#35]
This issue intends to provide some information which should help you to avoid some bugs or problems the ST community already solved - and had a hard time to do so / find the reasons for.

Only real ST plugins should be placed into the package root.

A "real ST plugin" ...

1. is a **standalone** python module, which
   - is not imported by any other python module
   - does not import another "real ST plugin" from the root directory.
2. implements at least one of ST's interface classes (e.g. `TextCommand`, `EventListener`, ...).

**The reason:**

Sublime Text loads every python module located in the root of a package via `importlib.import_module()` individually to check wheter it contains `Commands` or `EventListeners`. If such a module is then imported or was imported before by another module, python may hold 2 or more instances of this module in memory - especially after realoading the package. 

It may trigger painful issues if globals are used to store settings or states of the plugin as they are no longer shared between modules but may exist several times.

**The suggestion**

1. At least all modules which are imported by others, should be placed into a sub directory to hide them from ST's plugin loader. (E.g.: `utils.py`, `config.py`, ..).
2. To avoid any kind of possible issues, most of us even put all plugins into a package (sub directory with an `__init__.py`) and just leave one `plugin.py` or `main.py` in the root, which just imports all plugin interface classes to make them visible to ST. This way ST sees only one big plugin.

This approach implies some extra work to make sure the modules in the sub directories are properly reloaded during package upgrades, but this is often not more then just clearing the `sys.modules` cache before any import takes place in the main `plugin.py`.

The main plugin could look like this

```python
import sys
import sublime

if int(sublime.version()) >= 3114:

    # Clear module cache to force reloading all modules of this package.
    prefix = __package__ + "."  # don't clear the base package
    for module_name in [
        module_name
        for module_name in sys.modules
        if module_name.startswith(prefix) and module_name != __name__
    ]:
        del sys.modules[module_name]
    prefix = None

    # Import public API classes
    from .core.command import MyTextCommand
    from .core.events import MyEventListener


    def plugin_loaded():
        """
        Initialize plugin
        """
        pass

    def plugin_unloaded():
        """
        Complete tasks.
        Cleanup package caches.
        Exit threads.
        """
        pass

else:
    raise ImportWarning("Doesn't support Sublime Text versions prior to 3114")

```

Examples to see how to do it, are:

- A File Icon
- FileManager
- GitGutter
- Package Control
- PackageDev
- Terminus
- UnitTesting
- ...

**Comment by sergeche** [comment]
Seems like I have to do another refactoring of Emmet plugin 😂
Thanks for the heads-up, indeed, I’ve put everything into the root just to simplify editing cycle. My main concern about this approach: how should I reload main plugin if any dependency was changed?

**Comment by deathaxe** [comment]
It's really cool to see a pure python implementation of Emmet.

I didn't study any plugin in detail. If they are independend from each other they may stay in the root directory. They should just not import each other.

With the approach above all modules from the sub directories are automatically reimported/realoaded as soon as the main plugin changes on disk (`ctrl+s` is enough).

ST reloads it via `importlib.reload()` then, which triggers the loop to remove all modules from all sub directories from `sys.modules`. (It's important to keep the loop in front of any import.)

It may be a bit annoying to always need to keep the main plugin open and save it to see changes of dependencies being applied, but it works.

An alternative is the _AutomaticPackageReloader_ plugin, It reloads the main plugin, via key binding or (if enabled via settings) if any of the sub modules is saved.

**Comment by sergeche** [comment]
Some of them depend on each other, but it’s perfectly possible to move all the logic in separate submodule and keep only a single file in the root. I think I’ll use some sort of watcher which will `touch` main file if any of submodules change.

BTW, I just announced public beta of new Emmet plugin, going to release it into main channel soon :)
https://teletype.in/@chikuyonok/emmet2-sublime-text

**Comment by deathaxe** [comment]
You could add a `.python-version` with the `3.8` as content. It enables emmet to run in the python3.8 plugin host in ST4.

**Comment by sergeche** [comment]
Is it possible to get ST4 somewhere to check if Emmet works as expected?

**Comment by deathaxe** [comment]
It's available on Discord for licenced users. https://discord.com/invite/D43Pecu should lead you there.

**Comment by sergeche** [comment]
Moved all non-ST code into separate lib folder, plugin now uses a single file as entry point
