### ISSUE TITLE
Customize font, color and background of preview popup

### ISSUE THREAD

**Issue by DiegoAz** [emmetio/sublime-text-plugin#36]
I tried to modify the font, color and background to match my color scheme but it didn't work.

For example, to change the font I tried (.tmTheme file)

```xml
<key>popupCss</key>
<string>#emmet-preview-popup{font-family:"Operator Mono Book";}</string>
```

Can these values be changed?

**Comment by DiegoAz** [comment]
Yes

https://www.sublimetext.com/docs/3/color_schemes.html#global_settings-css

According to the link above:

> Plugins that use minihtml are encouraged to set a unique id attribute on the <body> tag of generated HTML to allow color schemes to override default plugin styles.

Although I have modified some plugins before (SublimeLinter) I am not an expert.

**Comment by sergeche** [comment]
OK, thanks, will update plugin according this doc

**Comment by sergeche** [comment]
I think you should use `<key>popup_css</key>` instead of `<key>popupCss</key>`?

**Comment by DiegoAz** [comment]
You can write color schemes using two file types: `.sublime-color-scheme` and ` .tmtheme`

- popup_css is for the "new" file type `.sublime-color-scheme`
- popupCss is for the old file type[ .tmThme](https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html#global_settings)

**Comment by sergeche** [comment]
OK, I see. Anyways, I actually followed recommendations described in doc above, don’t know why it’s not working. You can also try to use more specific selector like `#emmet-preview-popup .markup-preview { ... }`, maybe that would help

**Comment by DiegoAz** [comment]
Tried but it doesn't work. Although it works with other properties like `background-color`. Another issue is that I can't overwrite the value of `font-size` that you set in `11px` (in the color scheme file). The only way is extracting your package with the PackageResourceViewer package and modifying the `abbreviation.py` file directly. Maybe there's something we don't know or some problem in Sublime. I'm going to ask on the Sublime Forum. Thank you for checking this issue so quickly

**Comment by DiegoAz** [comment]
I find [this](https://forum.sublimetext.com/t/change-popup-font/48488/2).

> Without a font-family being defined by a stylesheet the popup uses the editor’s font by default.

But in this case that's not happening.

**Comment by sergeche** [comment]
I’ve added `popup_css` Emmet config to override CSS in Emmet popups and phantoms in v0.4.2. 
Yet still it seems like `font-family` is not applied.

**Comment by DiegoAz** [comment]
How do I test that setting?

**Comment by sergeche** [comment]
You should go to Preferences > Package Settings > Emmet2 > Settings and update `popup_css` property there

**Comment by DiegoAz** [comment]
Yes, I was able to change `font-size` but not the `font-family`. But If I change the color-scheme I will need to change that setting in order to match the new color-scheme. I think the best option is let the color-scheme apply the styles, that way, the color scheme authors set the best colors.

**Comment by sergeche** [comment]
I think you can also change colors via color-sheme. I followed ST recommendations about styles

**Comment by DiegoAz** [comment]
I tried but it didn't work.

One thing to emphasise is that I have color schemes in the` .tmTheme` format and I have rules changing the font to Operator Mono, for example I changed the font of the popup that show the scopes:

`#show-scope a{font-family:"Operator Mono Book"}`

**Comment by sergeche** [comment]
I think you should ask ST devs about changing font in popups. I didn’t set any specific font in popup

**Comment by DiegoAz** [comment]
I opened a new topic asking for help.

https://forum.sublimetext.com/t/change-popup-and-phantom-styles-in-emmet-2-plugin/53086
