### ISSUE TITLE
I often miss the buttons and the underline disappears.

### ISSUE THREAD

**Issue by jt3k** [emmetio/sublime-text-plugin#37]
subj.

For example, I enter `ul>li>o;>li` and I see only the last `li` underlined.

**Comment by sergeche** [comment]
`;` is invalid character for abbreviation so Emmet think that you’re typing regular text, not abbreviation. If you entered invalid characters, you have a chance to delete them and abbreviation will be automatically restored.

Another option is to enter abbreviation mode via `Emmet: Enter Abbreviation Mode` command: it will create a forced tracker and you can basically type anything there, Emmet will validate it and notify you if something goes wrong.
