### ISSUE TITLE
Performance issue when there is a lot of text in the tooltip

### ISSUE THREAD

**Issue by jt3k** [emmetio/sublime-text-plugin#39]
there's a performance problem.
When I type `div>lorem*43210` , my sublime editor is hanging.

This happens because the tooltip contains a lot of text.

To solve this problem, we can replace repeating parts with an equivalent text in this hint: for example 
`<div>lorem ipsum repeats 43210 times...`.

**Comment by sergeche** [comment]
Is it a real use case?

**Comment by jt3k** [comment]
not sure about that
