### ISSUE TITLE
Unwanted HTML element expansion in Vue SFC

### ISSUE THREAD

**Issue by rchl** [emmetio/sublime-text-plugin#42]
Should not expand `nonD` in this context:
![Screenshot 2020-08-17 at 12 38 36](https://user-images.githubusercontent.com/153197/90387642-d6ab2000-e086-11ea-8b5d-b60415b75440.png)

as this context is basically javascript code and not HTML. I want the language server to handle completions in this case.

Currently, it expands to:
![Screenshot 2020-08-17 at 12 39 22](https://user-images.githubusercontent.com/153197/90387731-fb9f9300-e086-11ea-982e-fe129d830aba.png)

**Comment by rchl** [comment]
Hmm, even though I've reproduced on the screenshot, I can't repeat that easily...

But I can reproduce 100% in this context (no space before `}}`) which might be due to ST issue as there is no `source.js` scope here for some reason:
![Screenshot 2020-08-17 at 12 45 18](https://user-images.githubusercontent.com/153197/90388045-841e3380-e087-11ea-99e5-7950e37c9384.png)

**Comment by sergeche** [comment]
Thanks for pointing out, totally forgot to add support for activation scopes from settings. Should be fixed in v2.0.5. You can use `ignore_scopes` and `abbreviation_scopes` from Emmet preferences to tune abbreviation gan be activated

**Comment by sergeche** [comment]
BTW, do you know if there’s a way to approve PR? https://github.com/wbond/package_control_channel/pull/8010
Trying to switch users to new Emmet version

**Comment by rchl** [comment]
Thanks :)

> BTW, do you know if there’s a way to approve PR? [wbond/package_control_channel#8010](https://github.com/wbond/package_control_channel/pull/8010)
> Trying to switch users to new Emmet version

@FichteFoll goes through PRs every now and then so he will get to it eventually. :)

**Comment by rchl** [comment]
BTW. Can you tag a new release? I'd like to try your changes but don't want to switch to cloning the repo manually.

**Comment by rchl** [comment]
Well, you seem to be creating tags but maybe PC needs a github release to pick it up?

**Comment by sergeche** [comment]
I’ve changed repository URL, it’s http://emmetio.github.io/sublime-text-plugin/registry.json now (hosted on GitHub Pages)

**Comment by rchl** [comment]
Works great. :)
