### ISSUE TITLE
Weird behavior of the preview when typing css property

### ISSUE THREAD

**Issue by rchl** [emmetio/sublime-text-plugin#44]
![Screen Recording 2020-08-18 at 11 20 58](https://user-images.githubusercontent.com/153197/90495590-133d5100-e145-11ea-987c-fa6a707117a6.gif)

Here I'm typing slowly:
 - `c` - shows preview for `color`
 - `o` - shows preview for `counter-reset`
 - `l` - the letter is inserted after the preview
 - `o` - the preview is changed to assume that I'm typing something custom (I guess)

So the possible issues are:
 - on typing `l`, the letter should not jump to after the preview
 - when `col` is typed, should it show preview for `color`?

I guess I might have wrong expectations as these are emmet abbreviations and not normal completions but at least the issue with the letter jumping after the preview should be valid.

**Comment by sergeche** [comment]
Can’t reproduce error for `col` with `l` after preview: works fine for me. Maybe something in console?

As for `co` which displays `counter-reset` instead of `color` — yes, it’s a known quirky behaviour: Emmet matches abbreviations agains snippet names, in this case it matched with `cor` snippet.

**Comment by rchl** [comment]
Can you try with `scss` file using `Packages/Sass/Syntaxes/SCSS.sublime-syntax` syntax (`Sass` package).
If you won't be able to reproduce I can dig deeper.
(Nothing in the console)

**Comment by sergeche** [comment]
That was a tricky case for SCSS syntax: when you type `co` it’s selector is `source.scss`, but when it becomes `col`, it becomes `meta.selector`, which is forbidden for abbreviation activation. So Emmet mistakenly ignored update, even if abbreviation exists.
