### ISSUE TITLE
Short snippets of text expanded as tags in HTML context

### ISSUE THREAD

**Issue by akella** [emmetio/sublime-text-plugin#45]
First of all thank you for amazing package!
I'm not sure if its bug or not, but i better ask:
If i type `di` in HTML context, Emmet recognises that as a "tag", and expands that to `<di></di>`. Even tho i have
```
"markup_style": "html",
```
Shouldnt that prevent expanding non-valid HTML tags? Or is it constraint, because of `abbreviation capturing` method?
The real problem i have - i've had a snippet assigned to that `di`, so im thinking how could i use it now.

**Comment by sergeche** [comment]
No, currently Emmet expands any entered word as abbreviation. I can add option to expand only known tags or matched snippets.

In your case, you should be able to see your snippet in popup and pick one if it’s displayed. Also, you can reset captured abbreviation with <kbd>Esc</kbd> key and expand with <kbd>Tab</kbd> as regular snippet

**Comment by akella** [comment]
> I can add option to expand only known tags or matched
May be that makes sense in specific HTML context, so that users wont get some typos expanded like: `<talbe>` or `<spn>`. But decision us up to you.

Works with Esc reset key for me, but i dont get anything in popup, just this: https://imgur.com/a/IMqCSvd. I only start to see previews when i do more complicated snippets like: https://imgur.com/a/sXPtrCi

**Comment by sergeche** [comment]
> Works with Esc reset key for me, but i dont get anything in popup
I mean default ST popup with snippets. You should be able to pick default snippet, although it’s not displayed by default (like in CSS or JS), you can manually invoke it with Ctrl-Space

**Comment by andremacola** [comment]
Emmet should expand only if is a known keyword. In css for example if you type `hei` and try to tab, emmet will cancel sublime default snippet and complete with `hei: ;`.

In Sublime Text 4 you have to type `esc` two times to cancel underlined emmet and tab times to sublime autocomplete.

I think there is a better way to handle this than `auto_mark` option.

![emmet](https://user-images.githubusercontent.com/3408809/90839240-6114ad80-e32d-11ea-98ab-ad45ccf1505c.gif)

**Comment by rchl** [comment]
> Emmet should expand only if is a known keyword.

Not by default. Or at least only in plain HTML as in Vue SFC the elements can be named anything.

As for having to cancel/complete twice, it's probably more like this issue https://github.com/emmetio/sublime-text-plugin/issues/3

**Comment by andremacola** [comment]
You are right about React, Vue etc...

But I think in css type files (css, sass, scss, less etc) need to be straightforward, input `hei` than `tab` should never autocomplete with `hei: ;`

**Comment by sergeche** [comment]
> One note – CSS abbreviations aren't working in source.scss files for me (they do work in plain CSS). I'm using this package for Sass syntax highlighting https://packagecontrol.io/packages/Sass.

The problem is that this package highlights selectors too early, and selectors are out of abbreviations scope. However, you can tune capturing behaviour with `abbreviation_scopes` Emmet settings, you can add the following selector: 

```
"source.scss - meta.property-value - meta.property-name - string - punctuation - comment"
```

Note that with this selector you’ll have abbreviation capturing in some unexpected places. I’ll try to figure out how to improve it.

> Also, is it possible to configure the captured abbreviation to not underline (I want to keep the behavior, I just find the constant underlining distracting)?

Yes, you can change `marker_scope` Emmet setting, you can set it, for example, to `"comment"` to make it less distracting or set empty string to make it invisible

**Comment by dylanfisher** [comment]
That's great, thank you!

**Comment by andremacola** [comment]
The author of  https://packagecontrol.io/packages/Sass already said he will update the completions to follow the new ST standards.

I'm made a custom sass package forked from his but updated with ST4 new CSS completions. And emmet is working fine. It's not public because only works with .scss files which is what I use.

**Comment by sergeche** [comment]
Pushed v2.1.3, should fix issue with SCSS
