### ISSUE TITLE
Tab key hijacking in version 2

### ISSUE THREAD

**Issue by dylanfisher** [emmetio/sublime-text-plugin#46]
Hi! I saw that emmet updated to version 2 in my editor this morning and I'm wondering if I need to configure emmet in a particular way to achieve similar behavior to version 1. Emmet now hijacks tab autocomplete of my custom HTML snippets in a way that I never experienced previously.

> Tab key hijacking: Emmet binds Tab key for expanding abbreviations so user is unable to insert native Sublime Text snippet or put tab right after word since almost every word can be abbreviation for Emmet.

This description sounds like what I am experiencing now, with v2. 

I'm also using https://github.com/matthewrobertson/ERB-Sublime-Snippets and these no longer work with emmet active.

Thanks a lot for your time!

**Comment by br4nnigan** [comment]
I use `auto_complete_commit_on_tab": true`

Now with the new version and `"tab expand": true` I can select a different value with arrow keys, but tab will always auto complete the initial value suggested by emmet.

Example: "mw" in css. I enter mw, emmet suggests "min-width", I select "max-width" in dropdown, hit enter, and I get "min-width". Emmet overrules the native auto complete.

If I'm not mistaken this worked in the previous version? Solution is to turn off the feature completely?

**Comment by sergeche** [comment]
@br4nnigan yes, unfortunately, there’s no workaround with this option enabled, it will be fixed in ST4. For now, you can disable `auto_mark` in Emmet and mimic old behaviour with this key binding:


```json
{
    "keys": ["tab"],
    "command": "emmet_expand_abbreviation",
    "args": { "tab": true },
    "context": [
        { "key": "emmet_capture_abbreviation" },
        { "key": "selection_empty" },
        { "key": "has_next_field", "operand": false },
        { "key": "auto_complete_visible", "operand": false },
        { "key": "selector", "operand": "source.css, source.sass, source.less, source.scss, source.stylus, source.postcss, source.jade, text.jade, source.pug, text.pug, text.slim, text.xml, text.html - source, text.haml, text.scala.html, source string" }
    ]
}
```

**Comment by br4nnigan** [comment]
> 
> 
> Hi, @sergeche. This doesn't work correctly.
> ![emmet](https://user-images.githubusercontent.com/20583184/90975273-6ba49200-e53b-11ea-9203-1c7b759a37f9.gif)

that works for me

**Comment by br4nnigan** [comment]
"tag_preview" option is pretty cool, why do you set it to false on default? just so you have some positive feedback among all the complaints.

**Comment by sergeche** [comment]
@br4nnigan a few people find new Emmet indicators a bit distracting so I disabled tag preview by default. Maybe later I’ll promote this feature to users and if feedback will be positive, I’ll enable it by default
