### ISSUE TITLE
Is there babel support?

### ISSUE THREAD

**Issue by Hubvill** [emmetio/sublime-text-plugin#51]
I have read the documentation and it states "Make sure your document syntax is set to JSX, not JavaScript". Is there a proper way to use Emmet with Babel so it functions like if the syntax was set to JSX? I have tried adding key binds that somewhat work, but I have the following issues: 

- No longer able to use the tab key to indent a line
- class is used and not className
- No preview

Here are my current key binds:

```
{
    "keys": ["tab"],
    "command": "emmet_expand_abbreviation",

    // put comma-separated syntax selectors for which
    // you want to expandEmmet abbreviations into "operand" key
    // instead of SCOPE_SELECTOR.
    // Examples: source.js, text.html - source
    "context": [
      {
        "operand": "meta.group.braces.round.js, text.html",
        "operator": "equal",
        "match_all": true,
        "key": "selector"
      },

      // run only if there's no selected text
      {
        "match_all": true,
        "key": "selection_empty"
      },

      // don't work if there are active tabstops
      {
        "operator": "equal",
        "operand": false,
        "match_all": true,
        "key": "has_next_field"
      },


      // don't work if completion popup is visible and you
      // want to insert completion with Tab. If you want to
      // expand Emmet with Tab even if popup is visible --
      // remove this section
      {
        "operand": false,
        "operator": "equal",
        "match_all": true,
        "key": "auto_complete_visible"
      },
      // {
      //   "match_all": true,
      //   "key": "is_abbreviation"
      // }
    ]
  },
```

**Comment by Hubvill** [comment]
Alright, I was able to reinstall Emmet now.

It seems that I am still unable to get Emmet to work with Babel JSX files. If I type `<ul>li.sample` and press tab, nothing happens. There is also no preview visible while I type.

**Comment by Hubvill** [comment]
Not sure if this is the proper way of doing things, but in the Emmet user settings ( `Preference ->Package Settings -> Emmet ->Settings` )  I ended up adding source.js to the syntax and abbreviation scopes. Sometimes I end up with the Emmet preview and js autocomplete showing at the same time, but if I press `Esc` then it shows just the Emmet preview.

Here are my Emmet user settings I have added:

```
"syntax_scopes": {
    "jsx": "source.js.jsx | source.tsx | source.js",
  },
  // List of scope selectors where abbreviation marker should be activated,
  // e.g. plugin will mark text that user types as abbreviation
  "abbreviation_scopes": [
    "source.js.jsx | source.tsx | source.js",
  ],
```

**Comment by sergeche** [comment]
Yes, that’s the right place to tune-up abbreviation capturing scopes. I ended up with the following: https://github.com/emmetio/sublime-text-plugin/commit/adfb0621ddc97c389a3e94fd0b0d15c4a9ff6a88

Will release it a bit later

**Comment by Hubvill** [comment]
Looks good. Closing issue.

Thanks!
