### ISSUE TITLE
Increment/decrement number no longer working

### ISSUE THREAD

**Issue by dylanfisher** [emmetio/sublime-text-plugin#52]
It seems like the increment number keyboard shortcuts no longer work in v2. I've tried in `.html` and `.css` and several other extensions.

**Comment by sergeche** [comment]
Shortcuts are not provided by default, too many users complained that Emmet takes overrides default actions and actions from other plugins: https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by dylanfisher** [comment]
OK I see. I'm working on remapping the shortcuts. If anyone else is looking for the previous mapping, you can find it in the old Emmet repo https://github.com/sergeche/emmet-sublime/blob/master/Default%20(OSX).sublime-keymap (there's other mappings per operating system). The new sublime-text-plugin package uses different action names are arguments, though, so you'll have to find and update those.

Sorry to raise so many issues right after the new launch – Sublime Text's method of updating packages doesn't make the update process very transparent.

I will say that I think it is a bit of a shame to disable Emmet's behavior as the new default. I never would have known about increment/decrement, or a lot of other Emmet features, had it not been for accidentally discovering them in Sublime. A better user experience in my opinion is to enable what you consider the best features (or in this case the features that were present in v1 of the package) and then make it easy for users to disable the features. That gives current users a seamless update, and users that complain the option to disable. Just my two cents, though. In any case, thanks for the time you dedicate to Emmet, it's a huge timesaver for me, and when the functionality is suddenly disabled, I realize all the more how essential Emmet's features are!

**Comment by samwood23** [comment]
@dylanfisher Thank you for raising - also find that removing this feature could have possibly been a "switch off" feature.
Can you point me in the direction of where/how to add the key mapping back into the plugin?

**Comment by sergeche** [comment]
Check out v2.1.3, there’s new menu item _Preferences > Package Settings > Emmet > Key Bindings_ with shortcuts from previous version, which you can copy and uncomment
