### ISSUE TITLE
Comment Function (|c) No Longer Working & Snippets Stopped Working

### ISSUE THREAD

**Issue by mikeoberdick** [emmetio/sublime-text-plugin#53]
Thank you so much for this plugin.  It has saved me TONS of time developing.  With that being said, I'm having a lot of issues with this new iteration which led me to roll back to the previous version.  I'd like to get the kinks worked out and then update.  One issue I was having that stumped me was when I was trying to use the comment feature.  I would type .col-md-8|c and then hit tab which used to output <div class = "col-md-8"></div>.  I was using a filter to get the last piece to work but it is now returning .col-md-8<center></center>.

Which setting would I need to adjust to get that working again?

Also, my custom user added snippets stopped working entirely for both scss and php...I have read through the issues but I don't see a fix for how to get the custom user snippets working in the new version.  

Here is my code from version 1 which was working (shortened for brevity):
`{
	"snippets": {
		"css": {
			"snippets": {
				"lgdown": "@include media-breakpoint-down(lg) {}",
			}
		},
		"html" : {
			"snippets": {
				"btn": "<a href = \"<?php echo \\$link['url']; ?>\"><button role = \"button\" class = \"btn\"><?php echo \\$link[\"url\"]; ?></button></a>",
			}
		}
	},
}`

And here is what I was trying to use for version 2:
`{
	"config": {
		"markup": {
			"snippets": {
				"btn": "<a href = \"<?php echo \\$link['url']; ?>\"><button role = \"button\" class = \"btn\"><?php echo \\$link[\"url\"]; ?></button></a>"
			}
		},
		"stylesheet": {
			"snippets": {
				"lgdown": "@include media-breakpoint-down(lg) {}"
			}
		}
	},
}`

When I would type btn and hit tab I got <button></button>.  If I typed another snippet (repeater) I would just get a normal tab movement jumping several spaces but no output.

**Comment by sergeche** [comment]
> I would type .col-md-8|c and then hit tab which used to output

Filters like `|c` are no longer available. Instead, you should either enable `comment` option in Emmet preferences (_Preferences > Package Settings > Emmet > Settings_) or use Tag preview feature: https://github.com/emmetio/sublime-text-plugin#tag-preview

> And here is what I was trying to use for version 2:

In Emmet 2, markup snippets are aliases to Emmet abbreviations. Your config should look like this:

```json
{
	"config": {
		"markup": {
			"snippets": {
				"btn": "a[href=\"<?php echo $link['url']; ?>\"]>button[role=button].btn>{<?php echo $link[\"url\"]; ?>}"
				}
		},
		"stylesheet": {
			"snippets": {
				"lgdown": "@include media-breakpoint-down(lg) {}"
			}
		}
	}
}
```

Or you can use native ST snippets, which work much better with new Emmet

**Comment by adragin** [comment]
Could you tell me how to remake my multi-line pieces of code after the update (from the snippets.json file)?

Like this:
"f1" : "<td style=\"font:${2}px/px Arial, Helvetica, sans-serif; color:#000;\">\n\t${1}\n</td>"

to code
```
	<td style="font:px/px Arial, Helvetica, sans-serif; color:#000;">
		|								
	</td>
```

**Comment by sergeche** [comment]
@adragin As mentioned above, snippets are just aliases to Emmet abbreviations:

```
"f1": "td[style='font:${2}px/px Arial, Helvetica, sans-serif; color:#000;']{\n\t${0}\n}"
```

**Comment by sergeche** [comment]
@adragin Also, it looks like the best solution for your example is to use native ST snippets, which work better with new Emmet version

**Comment by adragin** [comment]
that is, now custom code fragments cannot be used? no options at all?

**Comment by sergeche** [comment]
Custom code fragments are supported, you should write them as text node in Emmet abbreviations terminology, e.g. wrap with `{}`. Check out original snippets for examples: https://github.com/emmetio/emmet/blob/master/snippets/html.json

**Comment by mikeoberdick** [comment]
For reference, is there a use case where it makes more sense to create a snippet in Emmett or should they all just be created using native sublime text snippets?

**Comment by adragin** [comment]
coding emails was not an easy task anyway :(
before the update, I just translated frequently used code fragments into json and added a line to snippets. json, now I need to generate 80 files out of 80 lines ... the prospect is depressing ...

**Comment by sergeche** [comment]
@adragin You can perfectly use Emmet for your snippets, I just pointed out that you have more options with new version

**Comment by adragin** [comment]
in which section do I need to insert snippets for the inline css or section and style of the html file?

**Comment by sergeche** [comment]
No, these must be created as native ST snippets, Emmet is restricted to scopes outside HTML elements
