### ISSUE TITLE
Class chain not working

### ISSUE THREAD

**Issue by coreystinson2** [emmetio/sublime-text-plugin#54]
Update has broken multi-class support. Running fresh installation with default settings.

Reproduce:
`div.one.two [tab]` -> `div.<one class="two"></one>`

Expected:
`div.one.two [tab]` -> `<div class="one two"></div>`

**Comment by Falcikas** [comment]
I can confirm that `|c` commenting also broken.

**Comment by sergeche** [comment]
Please make sure abbreviation capturing works as expected: https://github.com/emmetio/sublime-text-plugin#expanding-abbreviation
If it’s not, specify syntax you are using

**Comment by coreystinson2** [comment]
Resolved, thank you.
