### ISSUE TITLE
Ctrl + shift + g - wrap is not working in sublime, after update. 

### ISSUE THREAD

**Issue by iampkmaurya** [emmetio/sublime-text-plugin#55]
ctrl + e for abbreviation expand not working like - mb:0px --- > margin-bottom:0px;

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by rvock** [comment]
I added a new key binding, but it does not work with multiple selections. It only expands the first selection :(

**Comment by sergeche** [comment]
@rvock what’s the use case of using multiple selections for wrapping?

**Comment by rvock** [comment]
Sorry, I meant "Expand Abbreviation". But both Commands do not work anymore with multiple selections.

The use case for me is editing of XML files. I often edit multiple places in the same XML file and need to write the same tags or tag structure. That's were expanding an abbreviation in multiple lines comes in handy.

**Comment by sergeche** [comment]
@rvock OK, got it, watch #48 for progress
