### ISSUE TITLE
Doesn't work for JSX

### ISSUE THREAD

**Issue by artdemo** [emmetio/sublime-text-plugin#56]
Stopped working after update. 
There is no problem with HTML, CSS and SCSS, only with JSX.

**Comment by sergeche** [comment]
In JSX, you should prefix abbreviations with `<`: https://github.com/emmetio/sublime-text-plugin#jsx-support

**Comment by artdemo** [comment]
Yeah, I know. But it seems like there is no presence of Emmet in JSX or JS file at all.

**Comment by sergeche** [comment]
What kind of presence do you expect? Do you see abbreviation preview when you type `<a`? What syntax do you use for JSX?

**Comment by artdemo** [comment]
Tried both, JSX and JS. There is no preview or autocomplete.

**Comment by sergeche** [comment]
Try to reinstall Emmet and restart ST

**Comment by artdemo** [comment]
Did it twice, still nothing. 
Just installed previous version and it works.

**Comment by sergeche** [comment]
Can you open ST console and check if there are any errors? Also, make sure you prefix Emmet abbreviations with `<` in JSX

**Comment by tdjsnelling** [comment]
Also not working in JSX for me. Not sure about artdemo, but I use the [Naomi](https://github.com/borela/naomi) package for JSX syntax, as I find it superior to the JSX package. Could this be the reason Emmet is no longer working for me? Previous versions were fine.

**Comment by sergeche** [comment]
Just pushed v2.1.4, it should have improved JSX support and work with Naomi. Note that Naomi automatically closes tags in this case so you may want to disable it if you want to use nested Emmet abbreviations

**Comment by artdemo** [comment]
I had the problem because of 'Simple JSX' package that i used for syntax highlighting. Now I have 'JSX' package installed and Emmet works as it have to.
Thanks for your help, Sergey!

**Comment by tdjsnelling** [comment]
Thanks @sergeche, seems to be working well now with Naomi
