### ISSUE TITLE
Change abbreviation preview select to a different key

### ISSUE THREAD

**Issue by russell-kitchen** [emmetio/sublime-text-plugin#57]
Is there a way to change the selection of what is previewed key? At the moment it is tab, but I have one one usable hand and constantly reaching over to tab is fairly inconvenient.

Also, is there a template for adding back shortcuts like `wrap_as_you_type`? I see the more actions in the docs but that doesn't help too much unfortunately.

Thank you!

**Comment by sergeche** [comment]
> Is there a way to change the selection of what is previewed key?

Yes, you can create you own shortcut for expanding. Use [this template](https://github.com/emmetio/sublime-text-plugin/blob/master/Default.sublime-keymap#L2-L10) and change `"tab"` in `keys` to any other shortcut

> Also, is there a template for adding back shortcuts like wrap_as_you_type?

Yes, it’s Wrap with Abbreviation now, you can follow these instructions: https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by russell-kitchen** [comment]
> Yes, you can create you own shortcut for expanding. Use this template and change "tab" in keys to any other shortcut

Rad, thank-you! Is there a way to only do this in stylesheet files? So it's only with this type of sotuation:
https://puu.sh/GldHz/b4089cbb96.png

And not expanding the markup abbreviation
