### ISSUE TITLE
Disable the prefixed abbreviations '<' in JSX

### ISSUE THREAD

**Issue by kevinleguillou** [emmetio/sublime-text-plugin#58]
Is there a way to use the old behavior from before 2.0 ?

I'm mostly writing markup and would like to be able to just write my abbreviations just like in HTML files. I don't mind the [downsides](https://github.com/emmetio/sublime-text-plugin#expanding-abbreviation).

**Comment by sergeche** [comment]
Will add option to disable prefix for JSX.

**Comment by mattfordham** [comment]
Is a disable option for this still gonna happen? ETA?

**Comment by sergeche** [comment]
It’s already available, see `jsx_prefix` Emmet setting

**Comment by mattfordham** [comment]
@sergeche Ah, thank you!

**Comment by kevinleguillou** [comment]
Tested on 2.2.6, setting `"jsx_prefix": false` works perfectly when using JSX syntax. Thanks!
