### ISSUE TITLE
Last update broke many things

### ISSUE THREAD

**Issue by kubiqsk** [emmetio/sublime-text-plugin#59]
1. write 'media' in CSS and press tab - nothing - in previous version it nicely print @media (CURSOR){}
2. in CSS after each property is missing semicolon - in previous version even single abbreviation ends with ;
3. not able to press CTRL + SPACE to finish closed abbreviation - in previous version it was working

Can I somehow make these work in new version? I checked settings, but there is nothing like that

I need to migrate to older version as my productivity goes down with this issues

**Comment by sergeche** [comment]
1. it was always `@m` or `@media` shortcut for media. You can create your own for `media` as described here: https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets
2. It looks like stylesheet abbreviations are not working at all. Do you see inline previews as in https://github.com/emmetio/sublime-text-plugin#css-support ? What syntax do you use for stylesheets?

**Comment by kubiqsk** [comment]
1
In previous version I wrote just media without @ 
I use it everyday as I'm a programmer, so I'm sure it was like that
Maybe something else was also updated and it's not just emmet issue?

2
Yes, I see this new green area while wiriting
for example I wrote p0 and I see that green area with padding: 0
that's ok, but there should be semicolon ; at the end
because then when I wrote another line I need to manually press ; at the end of each
yes I know I can use m0+p0 to create them together - it this case there are semicolons at the end of each line, that's correct

but next problem is when I press ESC or click somewhere, then that green area disappear and then when I press TAB it will only create tab space... I can press CTRL+SPACE and it works, but previously it was just TAB and years of writing code make me crazy when I need to do it differently now

**Comment by kubiqsk** [comment]
also "Wrap with Abbreviation" doesn't work for me anymore
i used ctrl+shift+g , now in documentation i see ctrl+shift+a but none of these works

**Comment by kubiqsk** [comment]
oh god, actually nothing works now... no Balance, no Select item

**Comment by rimzOK** [comment]
У меня та же самая проблема, я пытался сообщить об этом в другой ветке форума, часть свойств по таб просто не работает в css. в html когда убираешь курсор со строки при условном написании классов .item в надежде создать <div class="item"> это не срабатывает. Про css я вообще молчу.

**Comment by sergeche** [comment]
1. As I mentioned above, you can create your own snippets and use `media` to expand same snippet as `@media`. You can refer https://github.com/emmetio/py-emmet/blob/master/emmet/snippets/css.py for list of available snippets

> 2. for example I wrote p0 and I see that green area with padding: 0

There are two possible reasons: you are not in CSS syntax (maybe Sass?) or you’ve set `stylesheet.after` Emmet option to empty value.

> also "Wrap with Abbreviation" doesn't work for me anymore

See https://github.com/emmetio/sublime-text-plugin#more-actions for instructions about actions

**Comment by sergeche** [comment]
@rimzOK 
> У меня та же самая проблема, я пытался сообщить об этом в другой ветке форума, часть свойств по таб просто не работает в css

Можете написать, какие именно свойства не работают? И это именно CSS или препроцессоры?

> в html когда убираешь курсор со строки при условном написании классов .item в надежде создать </div class="item"> это не срабатывает.

Про это вообще не понял. Зачем убирать курсор и писать `</div class="item">`? Пишете аббревиатуру и жмёте Tab, всё должно работать

**Comment by kubiqsk** [comment]
i didn't change anything
i use same setup for years, but now after this update nothing works
where can i download older version? I don't see it here on git
can you please give me link?
Can i just extract it to \AppData\Roaming\Sublime Text 3\Packages\ and it shouldn't update anymore, right?

**Comment by sergeche** [comment]
@kubiqsk I’d like to fix issues with Emmet instead. Could you answer my questions above?

**Comment by kubiqsk** [comment]
I'm in CSS snytax, I don't use SASS or LESS or others
My user settings are only
`{
	"preferences":
	{
		"css.mozProperties": " ?? ",
		"css.mozPropertiesAddon": " ?? ",
		"css.msProperties": " ?? ",
		"css.msPropertiesAddon": " ?? ",
		"css.oProperties": " ?? ",
		"css.oPropertiesAddon": " ?? "
	},
	"telemetry": false,
	"uid": "ff1fcdae-ff54-4a5f-aa5d-09bc3b265a4f"
}`

my keymap is empty, so yes I have to create these keybindings now, but previously it worked, so it was probably in default keymap

**Comment by SeanHolt258** [comment]
I too can confirm that since updating I have run into many issues, much like the above. I work alongside 5 other front end developers who are all having issues today.

**Comment by sergeche** [comment]
@kubiqsk can you record a video with Emmet behavior in CSS?

@SeanHolt258 please describe issues you’re facing. Also, don’t forget to check out README for details

**Comment by sergeche** [comment]
> my keymap is empty, so yes I have to create these keybindings now, but previously it worked, so it was probably in default keymap

Keyboard actions are disable by default since lots of users were complaining about Emmet overriding default actions and/or actions from other packages

**Comment by kubiqsk** [comment]
nope, not even custom keymap
this is what i put there
```
[
	{
		"keys": ["ctrl+shitf+g"],
		"command": "emmet_wrap_with_abbreviation"
	}
]
```
and ctrl + shift + g still does nothing (I also restarted sublime)

**Comment by prwhitehead** [comment]
Firstly, I appreciate the time and effort you all put into this i really do. 

The last update changed my expand keybinding, then I had to search the docs to find out about the breaking changes to the shortcuts and the new system thats been implemented. 

Could this not be opt in? I cant expand markup in random files, it only seems to work in HTML files. I cant expand markup without hovering over the preview (that i don't want) which means moving my mouse to the area of the screen, rather than hitting `cmd+e` which I had before.

**Comment by sergeche** [comment]
@kubiqsk I see you have typo in `shift` of your keybinding

**Comment by rimzOK** [comment]
> 
> 
> @rimzOK
> 
> > У меня та же самая проблема, я пытался сообщить об этом в другой ветке форума, часть свойств по таб просто не работает в css
> 
> Можете написать, какие именно свойства не работают? И это именно CSS или препроцессоры?
> 
> > в html когда убираешь курсор со строки при условном написании классов .item в надежде создать </div class="item"> это не срабатывает.
> 
> Про это вообще не понял. Зачем убирать курсор и писать `</div class="item">`? Пишете аббревиатуру и жмёте Tab, всё должно работать

1) scss
2) условная ситуацию, я привёл как пример, если пишу например после точки .fgdfgfgdf-dfgdfg-dfgdf и отвлёкся, нажал эcкейп или пробел и не успел развернуть то всё хана, мне придётся писать конструкцию с самого начала если я поставлю как раньше курсор после этого куска текста, то развернуть уже не получится.

**Comment by kubiqsk** [comment]
i will start my old laptop with old version and I show yes before/after video
but it will be easier if I can download old version on my current laptop :/

**Comment by sergeche** [comment]
@prwhitehead 

>  I cant expand markup in random files

You can set `ctrl+e` keybinding to expand abbreviations everywhere. See https://github.com/emmetio/sublime-text-plugin#more-actions

> I cant expand markup without hovering over the preview (that i don't want)

Hovering is not required, previews are just for information only. If it doesn’t work, please create a new issue describing in detail about what’s happening

**Comment by KingMaraj** [comment]
How can we just implement the ST snippets we have setup?

**Comment by sergeche** [comment]
@rimzOK 

Про scss уже писал, что исправлено. Убедитесь, что стоит последняя версия плагина (2.1.4). Если всё ещё не работает, заведите новый тикет с примером. Важно показать код, в котором это не работает, так как Emmet определяет контекст, где можно разворачивать сниппеты

>  если пишу например после точки .fgdfgfgdf-dfgdfg-dfgdf и отвлёкся, нажал эcкейп или пробел и не успел развернуть то всё хана, мне придётся писать конструкцию с самого начала 

Не придётся, можно по Ctrl+Space активировать любую аббревиатуру: https://github.com/emmetio/sublime-text-plugin#expanding-abbreviation

**Comment by pokidovea** [comment]
Не работает Ctrl+Space. В JSX пишу
```jsx
<div.d-flex
``` 
и если пропадает хинт Emmet по какой-либо причине (поставил пробел, выбрал класс из выпадающей подсказки), то активировать аббревиатуру не удается ничем.
Удалял/ устанавливал плагин с нуля - не помогает

**Comment by sergeche** [comment]
@pokidovea пожалуйста, заводите новый тикет для таких вещей. Не надо всё в кучу сваливать

**Comment by prwhitehead** [comment]
> @prwhitehead
> 
> > I cant expand markup in random files
> 
> You can set `ctrl+e` keybinding to expand abbreviations everywhere. See https://github.com/emmetio/sublime-text-plugin#more-actions
> 
> > I cant expand markup without hovering over the preview (that i don't want)
> 
> Hovering is not required, previews are just for information only. If it doesn’t work, please create a new issue describing in detail about what’s happening

Hello, thank you for replying. 

I think there might be an issue as the "Key Bindings" menu item wasn't present in the menu initially, I had to restart before I could see it. 

I've added the following to the sublime-keymap: 

		{
				"keys": ["cmd+e"],
				"command": "emmet_expand_abbreviation"
		}

However it doesn't seem to work. I've tried it in JS, ERB, HTML files and it fails to expand the simple snippet `ul>li*4`.

**Comment by sergeche** [comment]
@prwhitehead it’s not `cmd+e`, it should be `super+e`: https://www.sublimetext.com/docs/3/key_bindings.html

**Comment by prwhitehead** [comment]
> @prwhitehead it’s not `cmd+e`, it should be `super+e`: https://www.sublimetext.com/docs/3/key_bindings.html

My apologies, I should have spotted that - trying to work at the same time as get it working again :)

**Comment by sergeche** [comment]
@prwhitehead BTW, abbreviation capturing with previews + expand with Tab should work in ERB as well. If it’s not, please create a new issue and describe what syntax to you use for ERB files

**Comment by SeanHolt258** [comment]
So there are several issues, the main one being that wrap with abbreviation no longer works.

Also, things such as lorem+number and TAB used to insert a defined amount of lorem ipsum. It just seems lots has stopped working or changed since the update. Is there not a simple way to downgrade to the last version?

Really appreciate this plugin and all the work that has gone into it, it has been a stable part of my workflow for several years. I just don't see why so many issues today, right after an update. Don't think its coincidence. 

Thanks

**Comment by sergeche** [comment]
@SeanHolt258 

> the main one being that wrap with abbreviation no longer works

It works, it just doesn’t have default keybinding. See https://github.com/emmetio/sublime-text-plugin#more-actions

> Also, things such as lorem+number and TAB used to insert a defined amount of lorem ipsum.

Should work as well. Make sure document syntax is set to HTML and you have most recent version of Emmet package (v2.1.4)

**Comment by a-y-u-s-h** [comment]
After adding:

```json
{
    "keys": ["ctrl+e"],
    "command": "emmet_expand_abbreviation"
}
```

1) Emmet doesn't expand JSX if it's not written with extension `.jsx` - undesirable. 
2) Emmet expands `h1.name` to `<h1 class="name"></h1>` inside JSX - undesirable.

Requesting the authors to please revert back the release. Too many issues with last update.

**Comment by SeanHolt258** [comment]
Hi Sergeche, 

I am on the most recent version...

I have tried to add my own key binding without success...

```
[
	{ "keys": ["ctrl+shift+g"],"command": "emmet_expand_abbreviation"}
]
```

The lorem+number+tab thing is working but only when outside of a tag, for example, if I do 

div>p `TAB` lorem50 `TAB`

Then nothing happens. When pre update I would of gotten this....

```
		<div>
			<p>Lorem ipsum dolor sit, amet consectetur, adipisicing elit. Error perferendis porro tempore beatae enim minus odit ducimus quae perspiciatis aliquid. Harum similique iure libero vel quia assumenda doloremque adipisci obcaecati? Facilis asperiores aliquid neque fugit rerum id. Autem dolorem libero iusto quae enim, recusandae cupiditate obcaecati, nam error, fuga earum?</p>
		</div>
```

**Comment by sergeche** [comment]
@a-y-u-s-h Emmet doesn’t look at file extension, it looks at current document syntax. Please check https://github.com/emmetio/sublime-text-plugin#jsx-support first

@SeanHolt258 yes, found that issue too, will release fix soon

**Comment by KingMaraj** [comment]
Surely you will be making everyones life much easier if you just reverted @sergeche

**Comment by a-y-u-s-h** [comment]
@sergeche Yup, correction - changing the document syntax gives the same effect.

**Comment by sergeche** [comment]
Please stop asking about reverting back to previous version: it has too much problems and lots of users (especially from Asia) cannot use it due to some network restrictions. Instead, help me to nail down all the issues with good error reports.

**Comment by sergeche** [comment]
@a-y-u-s-h please create new issue for it

**Comment by SeanHolt258** [comment]
@a-y-u-s-h Are you saying it works again now since you changed the syntax, or its still broken?

Also...

@sergeche Was that a decision on your part to remove the default key binding for "Wrap With Abbreviation"? Also if it is still working why does my custom keybind not work? Thanks

**Comment by sergeche** [comment]
@SeanHolt258 your command is `emmet_expand_abbreviation`, should be `emmet_wrap_with_abbreviation` for Wrap With Abbreviation

**Comment by a-y-u-s-h** [comment]
@SeanHolt258 @sergeche It's still broken after changing the document syntax: `h1.name` expands to `<h1 class="name"></h1>` in JSX. Though I still feel that all other document syntaxes should be supported because JSX is valid in all syntax documents and some people prefer to have syntax highlightings of JS and not JSX while writing JSX because JSX syntax highlighting packages are sort of poor.

@sergeche Umm, this may sound a bit cringey but maybe immediate next update with old code could resolve the issue if distribution of old version is the issue? I don't know.

**Comment by SeanHolt258** [comment]
Ok my bad, but it's still very broken. Doesn't seem half as precise as it used to be. Lets say I select a whole chunk of unformatted text which I want to wrap in <p>'s, I now seem to end up with a lot of empty <p>'s and also, the dialog box now opens above instead of below where you would usually input how you would like your text to be wrapped. 

Seems to be that its change for the sake of change if you ask me. Never had an issue with this before, always worked flawlessly, 100% of the time.

**Comment by sergeche** [comment]
@SeanHolt258 please create detailed issue for it: provide sample text and abbreviation you’re using to wrap

**Comment by sergeche** [comment]
> div>p TAB lorem50 TAB

Should work in v2.1.5

**Comment by a-y-u-s-h** [comment]
@sergeche maybe publish the older version too as Emmet Legacy? Should give thousands of developers some relief for the time being.

**Comment by KingMaraj** [comment]
I still only see version .14 through the Package Installer on Sublime, is .16 not the latest version now?

**Comment by SeanHolt258** [comment]
> @sergeche maybe publish the older version too as Emmet Legacy? Should give thousands of developers some relief for the time being.

![image](https://user-images.githubusercontent.com/70146318/91058475-68370680-e620-11ea-831e-e474da2ca7f7.png)

**Comment by sergeche** [comment]
@SeanHolt258 
> When before it would have left it neat and well-formatted without empty p tags.

Fixed in 2.1.7, empty lines should be removed. As for panel: yes, it moved to the top since it’s now uses panel, recommended by ST devs, and it also provides abbreviation validation when you type

**Comment by SeanHolt258** [comment]
> Fixed in 2.1.7, empty lines should be removed. As for panel: yes, it moved to the top since it’s now uses panel, recommended by ST devs, and it also provides abbreviation validation when you type.

Ahhh that's great, thanks. When will we be able to install through package control?

**Comment by sergeche** [comment]
Package is published automatically so it should be available every time I comment that something was fixed in version. You have to wait until Package Control updates its caches, maybe restart ST or reinstall Emmet package

**Comment by SeanHolt258** [comment]
![image](https://user-images.githubusercontent.com/70146318/91064106-be0ead00-e626-11ea-878d-d301cdac79b2.png)
Updated to 2.1.7. Thanks @sergeche

**Comment by SeanHolt258** [comment]
Not to be a nusance, although its loads better now... When I try for example this....

![image](https://user-images.githubusercontent.com/70146318/91064576-52790f80-e627-11ea-9ced-f1c9ffc9b36a.png)

Using `ul>li*` I get this...

![image](https://user-images.githubusercontent.com/70146318/91064698-82281780-e627-11ea-8616-3a5636c86fe1.png)

Notice the stray `TAB` 's in the first list item, same applies regardless of what kind of tag you use.

**Comment by sergeche** [comment]
@SeanHolt258 try to place start of selection right before `Chocolate` word. And please create new issue so I can improve indentation detection for wrapped content.

**Comment by SeanHolt258** [comment]
Yeah, that's fine! Works as expected I was just pointing out that historically that would not happen.  Indentation detection would be great! 

Can confirm that Lorem+number and TAB is working now even when nested within an element. 

I feel like this morning some CSS "auto-complete" functions were really buggy but have gotten better throughout the day, have you been working on these too??

![image](https://user-images.githubusercontent.com/70146318/91068419-2ad87600-e62c-11ea-8a96-6b35287f0d02.png)

Thanks for being so responsive on here. Emmet is the reason I use Sublime Text and not the other way around! 👍

**Comment by sergeche** [comment]
@SeanHolt258 thanks! Yeah, I was fixing bugs entire day, I understand my responsibility for Emmet users and their workflow so I've tried to fix bugs as soon as possible.

**Comment by kubiqsk** [comment]
So here is old emmet behavior
https://youtu.be/VGIO6aNctLQ

and new emmet behavior
https://youtu.be/Jui8hOOkiJ4

as you can see in old:
- media without @ works
- p0 expanded has semicolon at the end
- m0 when escaped is still possible to expand with tab
- wrapping works without leading spaces
- various keyboard shortcuts work without additional setup

**Comment by kubiqsk** [comment]
first of all, thank you for a great utility - it is really number 1 must-have item in my sublime (previously also in dreamviewer)

maybe it will be good if you create separate project called Emmet 2.0 and people can decide if they want this completely new UI and stuff... or if they are happy with old one

sometimes you simply create perfect solution on first try and you don't need to try make it better ;)

**Comment by sergeche** [comment]
@kubiqsk Thanks for detailed report. Indeed, there’s some strange issues with semicolon, I’ll investigate it. Can you send me contents of you `Emmet.sublime-settings` file? It’s available at _Preferences > Package Settings > Emmet > Settings_ menu item.

As for keyboard shortcuts, go to _Preferences > Package Settings > Emmet > Key Bindings_ menu item and copy uncommented actions you’re using from left to right.

As for `media`, here’s a snippet for you:

```
"media": "@media ${1:screen} {\n\t${0}\n}"
```

Put in into "stylesheet" section as described here: https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets

**Comment by sergeche** [comment]
Fixed wrapping without leading spaces in v 2.1.10

**Comment by kubiqsk** [comment]
it is in my previous comment
https://github.com/emmetio/sublime-text-plugin/issues/59#issuecomment-679103913

**Comment by ifaniqbal** [comment]
Anyone experienced unable to execute certain commands?
#83

**Comment by br4nnigan** [comment]
All this just lead to me disabling emmet alltogether :(

**Comment by kubiqsk** [comment]
For anyone who need to make it works immediately and can not wait for fixes:

Preferences > Package Settings > Package Control > Settings - User
{
	"auto_upgrade_ignore":
	[
		"Emmet"
	]
}

Then copy this: https://files.kubiq.sk/Emmet.sublime-package
to your \AppData\Roaming\Sublime Text 3\Installed Packages\

**Comment by sergeche** [comment]
@kubiqsk Please report problems you’re struggling in new Emmet as separate issues. Most of the the problems you described earlier has been already fixed

**Comment by paulmist** [comment]
I agree that we should be working to help fix issues with the new version… but…

If you're in a mission critical situation and don't have the time to deal with the (unfortunately numerous) bugs then you can still manually install the previous version:

https://github.com/sergeche/emmet-sublime#how-to-install

It perhaps would have been good to have the new version as an opt-in.

**Comment by sergeche** [comment]
@paulmist I'm just curious about which mission critical situations you have with free and open-source tool that just helps you write code faster?

**Comment by paulmist** [comment]
Hi, @sergeche - that's quite a loaded question.

In short, situations where you're working at top-speed to deliver client work where you've come to rely on your tools working as you expect them to and have expected them to for some time.

If I were to throw in a rogue analogy - say I was a delivery driver. I've got a time slot to hit but it's not a problem. I start my van and suddenly the gear stick is rearranged. I've got to re-learn that. Even if it is a more efficient layout my muscle memory is going to grind the gears every now and then and I may stall the engine from time to time.

I'm excited for the tool to evolve but if it's a substantial change I want the option to jump in when I'm ready.

**Comment by sergeche** [comment]
@paulmist I see. You’re making money using free tool but don’t want to support it by any means. And you expect it to be a commercial-quality (spend more time to fix bugs, consider unexpected use cases from thousands of developers) and still remain free for you.

And I’m not talking abound financial support only (which is [pretty upsetting](https://github.com/sponsors/emmetio), by the way, assuming [how many developers use it](https://packagecontrol.io/packages/Emmet)). Not even PRs from users with bugfixes. I’m just asking about a good error report describing what exactly doesn’t work as expected and read README first. That’s all. But everyone’s in rush, driving their vans to make it up in a time slot, assuming someone else should maintain vans.

**Comment by paulmist** [comment]
Thanks again for responding.

You've made a lot of negative assumptions here which is a shame.

If I find myself able to help, report etc. I certainly will.

**Comment by kubiqsk** [comment]
Hello,
after a long time I decided to try the new version again and I must say, it's really good ;)
Here are few issues I'm still struggling with:

(*I'll use this | as a cursor position)

### Missing semicolon in expanded values in CSS in @media

It works for code like
```
#test{
    db|
}
```
it becomes
```
#test{
    display: block;
}
```

but when you're inside @media, then

```
@media (max-width: 767px){
    #test{
        db|
    }
}
```

becomes

```
@media (max-width: 767px){
    #test{
        display: block
    }
}
```

Missing semicolon means inconsistent behavior and it becomes even worse, when you want to use more attributes like `m0+p0` - then there are missing semicolons everywhere

### Expand HTML in PHP not working

Again I'm referring to previous version and I'm used to use it this way

```
<?php
echo 'div.test|';
?>
```

should became this, when I press [TAB]

```
<?php
echo '<div class="test">|</div>';
?>
```

Yes, I know I can use [Ctrl+E], but why not [TAB]? Previously it worked and I would really like to make it works again.
How to do it please?

---

For now, this is what I realized in 2 days of using new version, so thank you for a great work and let's fix this to make it perfect ;)

**Comment by kubiqsk** [comment]
I found another issue
In my config I have
```
"config": {
	"css": {
		"snippets": {
			"trr": "transform: rotate(${1:45}deg);",
		}
	}
}
```
but when this abbreviation expand in the CSS it, looks like this
```
transform: rotate(45 deg);
```
the space after 45 is incorrect and it can not be there

**Comment by kubiqsk** [comment]
I found another bug

`c#0d4c1d`

is expanded to

`color: #d04c1d;`

which makes no sense

**Comment by kubiqsk** [comment]
@sergeche , @Shakil-Shahadat is anyone reading this? :D Please let me know if it makes sense to write it here or not. Thank you ;)

**Comment by sergeche** [comment]
@kubiqsk it’s better to create separate issues for your last comments. It’s hard for me to follow bugs and feature requests in such threads.

**Comment by kubiqsk** [comment]
Separate / new issue opened
https://github.com/emmetio/sublime-text-plugin/issues/166
