### ISSUE TITLE
User sublime snippet are overridden by Emmet since update

### ISSUE THREAD

**Issue by JBLRC** [emmetio/sublime-text-plugin#61]
I'm used to my custom multi-line snippets but since last update they are not working anymore on Ubuntu :

example (bpxs.sublime-snippet in Packages/User folder) : 

`<snippet>
	<content><![CDATA[@include bp(xs){
	${0}			
}]]></content>
	<tabTrigger>bpx</tabTrigger>
	<scope>source.scss</scope>
</snippet> 
`

Adding snippets in Emmet.sublime-settings is not enough for me since my snippets are more complex with multiple lines.

They are working again when I uninstall Emmet.

**Comment by sergeche** [comment]
That’s the common problem of Emmet snippets vs. native ones. `bpx` is resolved by Emmet into `background-position-x`.

You have a few options here:

1. When you write `bpx`, ST should display autocomplete popup with you snippet. You can use Enter key complete it, or press Esc first to reset Emmet abbreviation then Tab to expand native snippet.
2. You can move this s snippet to Emmet as [described here](https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets). Multiple lines are supported as well, see https://github.com/emmetio/emmet/blob/master/snippets/css.json#L2 for reference

**Comment by JBLRC** [comment]
that will do the trick, thanks :)
