### ISSUE TITLE
New update not working with scss variables.

### ISSUE THREAD

**Issue by eriku** [emmetio/sublime-text-plugin#62]
Leaving out all the other issues I've been dealing with all morning, wasting hours trying to figure out the new update and costing me a bunch of money, the latest issue I've been having is this for example:

What it's doing: `bgc$c_bg-dark` = `background-color: -dark;`
Should be: `bgc$c_bg-dark` = `background-color: $c_bg-dark;`

**Comment by eriku** [comment]
Please give those of us that use Emmet for work a link to download the older version until this new update has the majority of bugs worked out.

**Comment by sergeche** [comment]
> until this new update has the majority of bugs worked out

Please create issues for this majority of bugs

**Comment by eriku** [comment]
I guess you're not going to fix the issue I pointed out.

**Comment by eriku** [comment]
I guess you're not going to fix the initial issue that I point out (see below). I'm going to go back to using https://github.com/sergeche/emmet-sublime even though it's no longer supported.

What it's doing: `bgc$c_bg-dark` = `background-color: -dark;`
What it should be doing: `bgc$c_bg-dark` = `background-color: $c_bg-dark;`

**Comment by sergeche** [comment]
It’s fixed in v2.1.16. Issue is closed automatically with commit that fixed issue: https://github.com/emmetio/sublime-text-plugin/commit/55542bf3a3692dda3e7a63712ea85d1c67138397

**Comment by eriku** [comment]
I updated to 2.1.16 and it's still not working.

**Comment by sergeche** [comment]
Just made clean install of Emmet package and it words for me. Did you installed in from Package Control or manually?

**Comment by eriku** [comment]
Package Control. I removed Emmet, re-installed Emmet, restarted Sublime. Didn't work. I unfortunately can't keep dealing with this as it's costing me money so I am completely removing the new version and going back to the old repo.
