### ISSUE TITLE
Evaluate Math Expression shortcut broken in update

### ISSUE THREAD

**Issue by howeller** [emmetio/sublime-text-plugin#66]
(⇧⌘Y) doesn't run the evaluation as it had previously.

**Comment by sergeche** [comment]
Shortcuts are not enabled by default since too many users complained about them. You should enable them manually: https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by howeller** [comment]
Where can I find the original binding to create the shortcut?
Thank you for responding. I know you've got a lot of work in front of you and appreciate your efforts.

**Comment by sergeche** [comment]
By the link above there's descriptions about how to modify shortcuts: when you open Preferences > Package Settings > Emmet > Key Bindings menu item: there are examples of commands and shortcuts

**Comment by howeller** [comment]
Thank you!
