### ISSUE TITLE
Increment/Decrement Number Unexpected Behavior

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#68]
I enabled the keyboard shortcuts to increment/decrement numeric values, then I noticed erratic behavior that was different than the previous version of Emmet.

In a file set to HTML syntax, enter 20 blank lines (the actual number is irrelevant, but it helps to have several).  On line 10, type 100 by itself (this number is irrelevant, also).

With the caret on or touching the 100 value, try to increment or decrement the value.  The first keystroke results in the value being moved upwards by one line, then the value is placed in a selection region.  Once the value is selected, __and remains selected__, the increment/decrement operation works, as expected.  The previous version of Emmet did not require the number to be selected.

**Also, notice that number of lines in the file has been reduced by one.**  Deselect the number and repeat the increment/decrement operation.  The number shifts upwards, removing a line from the file and then is selected, at which point the operation can be successfully repeated.

From what I recall of the previous version of Emmet, when incrementing/decrementing numbers, the number did not need to be selected before running the inc/dec command, nor was the number automatically selected after the command.

I would also like to add that Ctrl+Shift+Up/Down Arrow is set to move the current line, or selected lines, up and down, as expected.

This is with Sublime Text 3.

Thanks!

**Comment by sergeche** [comment]
There's no need to select number to increment it, it should work as expected. Maybe you have the same keybinding that moves line up?

You can try the following:
- Restart ST to unload previous version of Emmet, in case if it wasn't unloaded properly after update.
- Open ST console and run `sublime.log_commands(True)`, it will log all commands. Check out which commands are performed when there's no selection

**Comment by michaelalandawson** [comment]
I restarted ST to update Emmet:

`Package Control: Upgraded Emmet to 2.1.10`

I added 20 blank lines.  On line 10, I added the number 100 by itself.  I did not select the number.

I pressed Ctrl+Up Arrow.

Result:

The number moved from line 10 to line 9
The value incremented from 100 to 101
The value was selected

The only command that executed during this operation was:
`command: emmet_increment_number {"delta": 1}`

As before, this works properly only if the number is selected __before__ I try to increment/decrement the number.

ST3 3.2.2 Build 3211

**Comment by michaelalandawson** [comment]
Here is another related issue.

On a blank line, type the number 1000 by itself.

Select the second and third digits of this number. In other words, select the two zeros in the middle of the number.

Run the increment command.

The value is changed from 1000 to 110.

From what I recall, the previous version of Emmet would have expanded the selection to grab the entire number and increment it.  However, again, the previous version didn't use actual selection regions.

Therefore, I would have expected the result to have been 1010 (retain leading zero) or 1001 (expand selection to all adjacent numbers as with previous version of Emmet).

I can't say whether this is correct or incorrect behavior. It is different than before.  I kind of like the ability to select certain digits within a number and increment only the selected digits, however, I would have liked the leading zeros to be retained.

**Comment by sergeche** [comment]
Fixed in v2.1.11

**Comment by sergeche** [comment]
In next releases will fix leading zeroes

**Comment by michaelalandawson** [comment]
Thank you for the fixes.  I found another related issue.  This is pulled from the Emmet keymap file:

`    // {
    //     "keys": ["alt+up"],
    //     "command": "emmet_increment_number",
    //     "args": { "delta": 0.1 }
    // },
    // {
    //     "keys": ["alt+down"],
    //     "command": "emmet_increment_number",
    //     "args": { "delta": 0.1 }
    // },`

The delta for increment (alt+up) and decrement (alt+down) commands are both set to `0.1`.  The delta for the decrement command should be `-0.1`.

Thank you so much for your effort!

**Comment by vellkan** [comment]
Same here - this function stop working at all.

**Comment by sergeche** [comment]
@vellkan Please read whole thread: actions are working but have no default bindings. There's instructions how to enable them

**Comment by michaelalandawson** [comment]
@vellkan 

Have you copied the template key binding snippets from the Emmet file to your custom key bindings file?  That is required.  Also, make sure the snippets are not commented with leading "//" characters.  If you have completed these two steps, and saved the custom key bindings file, the bindings should work immediately.

**Comment by michaelalandawson** [comment]
@sergeche 

Thank you for fixing the inc/dec for decimal values (alt+up/down).  I have confirmed it works with v2.1.14.

**Comment by vellkan** [comment]
Now everything is working OK - after this upgrade.
