### ISSUE TITLE
abbreviation not displaying on ST 3

### ISSUE THREAD

**Issue by gaiahub** [emmetio/sublime-text-plugin#71]
tab works but i cant build abbreviations like `div>ul>li`
also when i type this i dont get code hints like your examples.

**Comment by sergeche** [comment]
Did you set document syntax to HTML?

**Comment by sergeche** [comment]
Can you restart ST, the open ST console and send me its contents?

**Comment by gaiahub** [comment]
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/mydoc/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/mydoc/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/mydoc/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Emmet", "Vintage"]
pre session restore time: 1.57332
startup time: 1.91932
first paint time: 1.92932
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin LESS.less_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
git: tracking working dir C:\xampp_5.6\htdocs\gaianet
reloading plugin Package Control.Package Control
git: tracking working dir D:\xampp-7.4.6\htdocs\client\client
reloading plugin Sass.sass_completions
reloading plugin Babel.Babel
reloading plugin Emmet Style Reflector.emmet_style_reflector
reloading plugin sublime-text-plugin-master.main
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\mydoc\AppData\Roaming\Sublime Text 3\Packages\sublime-text-plugin-master\main.py", line 18, in <module>
    from .lib import emmet_sublime, abbreviation, balance, syntax, comment, \
  File "C:\Users\mydoc\AppData\Roaming\Sublime Text 3\Packages\sublime-text-plugin-master\lib\emmet_sublime.py", line 3, in <module>
    from ..emmet import expand as expand_abbreviation, extract, Config
ImportError: No module named 'sublime-text-plugin-master.emmet'
reloading plugin SublimePrettyJson-master.PrettyJson
reloading plugin SublimePrettyJson-master.PrettyJsonListeners
plugins loaded
Package Control: No updated packages

**Comment by sergeche** [comment]
It seems like you’ve installed Emmet by checking out Git repo, not from Package Control. It requires additional.
This package requires additional module to be installer. Either try to install Emmet from Package Control, or download full package from https://emmetio.github.io/sublime-text-plugin/

Also note that if want to install it manually, you should remove `Emmet` from `ignored_packages` list

**Comment by gaiahub** [comment]
this is my option from Package Control
![image](https://user-images.githubusercontent.com/49032945/91198137-0b376100-e6b1-11ea-982f-b82012e84303.png)

**Comment by sergeche** [comment]
Try to remove `sublime-text-plugin-master` first, then try to remove `Emmet` from Package Control and try again. There were issue with Package Control, ended up in some broken package list

**Comment by gaiahub** [comment]
i delete those files and restart, then they reappear.

**Comment by gaiahub** [comment]
> remove Emmet from ignored_packages list
this did it, thank you!!!

**Comment by nalagg** [comment]
I am having a similar problem, here is my user settings
`{
	"detect_indentation": false,
	"font_size": 11,
	"ignored_packages":
	[
		"Vintage"
	],
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
`
