### ISSUE TITLE
Preference doesn't work anymore after update

### ISSUE THREAD

**Issue by tobipch** [emmetio/sublime-text-plugin#72]
After my Sublime Package Control updated Emmet this morning, the css.valueSeparator property doesn't work anymore.

`{
	"preferences":
	{
		"css.valueSeparator": ":"
	}
}
`

I added this preference to not have the space between the colon and the value in CSS.

**Comment by sergeche** [comment]
The option name has changed, it's `stylesheet.between` now. Also, the entire config format has changed: https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets

You should put this option into `options` map of `stylesheet` or `css` section in the example above

**Comment by tobipch** [comment]
Thank you. I managed to implement the settings like I wanted.

For reference if anybody else has this problem:

`{
	"config":
	{
		"stylesheet":{
			"options":{
				"stylesheet.between":":",
				"stylesheet.after":"; "
			}
		}
	}
}`

More options can be found here: [https://github.com/emmetio/emmet/blob/master/src/config.ts#L79](url)

Thank you for developing Emmet!!!
