### ISSUE TITLE
Not work with Pug after update

### ISSUE THREAD

**Issue by hqdrone** [emmetio/sublime-text-plugin#74]
I using Emmet with Pug, but after update no one abbreviations doesn't expanded

**Comment by hqdrone** [comment]
Fix it

Sublime Text Menu -> Preferences -> Key Bindings

Add to user keymap this command for Tab button: 

`
[
	{
		"keys": ["tab"],
		"command": "emmet_expand_abbreviation"
	}
]
`

**Comment by sergeche** [comment]
A better keybinding:

```json
{
    "keys": ["tab"],
    "command": "emmet_expand_abbreviation",
    "args": { "tab": true },
    "context": [
        { "key": "emmet_capture_abbreviation" },
        { "key": "selection_empty" },
        { "key": "has_next_field", "operand": false },
        { "key": "auto_complete_visible", "operand": false },
        { "key": "selector", "operand": "source.css, source.sass, source.less, source.scss, source.stylus, source.postcss, source.jade, text.jade, source.pug, text.pug, text.slim, text.xml, text.html - source, text.haml, text.scala.html, source string" }
    ]
}
```

Yes still please tell which syntax do you use, it should work automatically with previews, as in HTML

**Comment by hqdrone** [comment]
Thank you!

Without your keybinding I get this:
![3](https://user-images.githubusercontent.com/11762888/91169735-7fd5c400-e6e0-11ea-9c28-35c194e47687.gif)

Sublime Text 3 build 3211
Pug plugin: https://packagecontrol.io/packages/Pug
