### ISSUE TITLE
Triggers abbreviation in comment block

### ISSUE THREAD

**Issue by rchl** [emmetio/sublime-text-plugin#75]
Typing `<` in a comment block here triggers abbreviation and completing creates an HTML tag.
![Screenshot 2020-08-25 at 10 45 23](https://user-images.githubusercontent.com/153197/91153992-34f88400-e6c1-11ea-87b1-8d869ee0c7f8.png)

Scopes: `source.js comment.block.documentation.js`

**Comment by rchl** [comment]
Would this be OK:
```
"(source.js.jsx | source.tsx | source.js | source.jsx) - comment",
```
instead of current:
```
"source.js.jsx | source.tsx | source.js | source.jsx",
```
?

Or would it be too broad to exclude comments?

Also, I wonder if `source.js.jsx` is needed in that rule since there is already `source.js` that should match (I think).

**Comment by sergeche** [comment]
Yes, comment should be excluded from activation, totally forgot it
