### ISSUE TITLE
Emmet is no longer on the install list

### ISSUE THREAD

**Issue by joelthorner** [emmetio/sublime-text-plugin#76]
After the last update Emmet stopped working in HTML and CSS and I decided to remove and reinstall the plugin. 
Now it does not appear in the Package control installation menu.

Has something similar happened to anyone?

From yesterday to today I did not touch any configuration and the plugin broke.

😢

**Comment by navandstokes** [comment]
Same here. I was in the middle of reinstalling as well. On the [Package Control website](https://packagecontrol.io/packages/Emmet) it says "missing".

**Comment by tigiyev** [comment]
Same thing. 

After Emmet update has broke all of it core functions ( RIP .classname == <div class="classname"></div>) i decided to reinstall plugin. Now it does not appear in the Package control list.

I wonder maybe it happens because they still updating the plugin.

**Comment by joelthorner** [comment]
Luckily I have an old copy of the installed packages and I have made a backup to continue working but it is a temporary solution.

**Comment by sergeche** [comment]
There were reports that Package Control is a bit broken. You can download latest Emmet version from https://emmetio.github.io/sublime-text-plugin/
