### ISSUE TITLE
Are old preferences not working?

### ISSUE THREAD

**Issue by adragin** [emmetio/sublime-text-plugin#78]
Tell me please, are these settings no longer supported or I should somehow change the syntax?

```
	"preferences":
	{
		"css.valueSeparator": ":"
	}
```

**Comment by michaelalandawson** [comment]
This has been changed.  Refer to:

[Preference doesn't work anymore after update #72](https://github.com/emmetio/sublime-text-plugin/issues/72)

**Comment by adragin** [comment]
@michaelalandawson Thanks! No wonder they say that all the questions have already been asked by someone :)
