### ISSUE TITLE
Wrap with Abbreviation not adding Email or URL in href Attribute

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#79]
The previous version of Emmet would place a copy of the email address or URL when wrapping either of those with an anchor tag.

Example:

`lorem ipsum user@email.com dolor sit`
`lorem ipsum https://domain.com sit`

Previously, I could select the email address and URL, then wrap both of them with the A tag, in one operation.  The result would be:

`lorem ipsum <a href="user@email.com">user@email.com</a> dolor sit`
`lorem ipsum <a href="https://domain.com">https://domain.com</a> sit`

Now, the current version of Emmet won't auto-fill the href attribute resulting in:

`lorem ipsum <a href="">user@email.com</a> dolor sit`
`lorem ipsum <a href="">https://domain.com</a> sit`

This was a wonderful, time-saving feature of the previous version of Emmet.  It was very efficient with multiple selection regions.

**Comment by sergeche** [comment]
Indeed, forgot to implement that feature. Will fix it soon

**Comment by sergeche** [comment]
Should work in v2.1.19

**Comment by michaelalandawson** [comment]
Thank you. This is one of my most-used features of Emmet.
