### ISSUE TITLE
V2 no longer has the "input bar" at the bottom of the screen

### ISSUE THREAD

**Issue by Dakkers** [emmetio/sublime-text-plugin#80]
Not sure if this is intentional, but I preferred that UX instead of the new version. (It was accessed via `Ctrl+Alt+Enter`). Additionally, when I select some text and try to enter abbreviation mode, it doesn't wrap the selected text in the new abbreviation.

If possible, I'd like to know how to downgrade to v1. It would be much appreciated.

**Comment by michaelalandawson** [comment]
[Sergey](https://github.com/sergeche) moved it to the top [following the recommendation from the developers of Sublime Text](https://github.com/emmetio/sublime-text-plugin/issues/59#issuecomment-679178222).

**Comment by michaelalandawson** [comment]
Sergey also removed the default key binding because it conflicted with key bindings in other packages.  Look in Preferences > Package Settings > Emmet > Key Bindings.  It is commented in that file.  Copy it to your user key bindings file and apply whichever custom binding you prefer.

**Comment by sergeche** [comment]
> Additionally, when I select some text and try to enter abbreviation mode, it doesn't wrap the selected text in the new abbreviation

Abbreviation mode is used to enter new abbreviation with interactive preview and validation, for wrapping, use Wrap With Abbreviation instead

**Comment by Dakkers** [comment]
in this case:

```
    <div className='border-bottom'>
      {
        sections.map((section, i) => (
            [cursor goes here]
        ))
      }
    </div>
```

using `Wrap with abbreviation` will wrap the whole `{ ... }` with a div when I haven't actually selected any text. it makes sense but I'd like to use the same command to enter abbreviations and to wrap, as was the case with the older versions of Emmet. is this possible?

**Comment by sergeche** [comment]
@Dakkers there's Enter Abbreviation Mode command, which is much like default abbreviation capturing but stricter validation.

What's the reason to have separate command for abbreviation input?

**Comment by Dakkers** [comment]
@sergeche  what I mean is that `ctrl+alt+enter` in the old version would work for both non-wrapping and wrapping

**Comment by sergeche** [comment]
@Dakkers There's no need in separate command now: it was introduced for those who don't like that Emmet overrides Tab, basically blocking native ST snippets. You can bind this shortcut for Enter Abbreviation Mode, if you like. But for wrapping you should use Wrap With Abbreviation command

**Comment by Dakkers** [comment]
There is a need for separate commands though, because the normal "Enter Abbreviation Mode" doesn't work when wrapping, as you've stated. I used to use `Ctrl+Alt+Enter` in the previous version regardless of wrapping. Now I have to have 2 separate commands, 1 for wrapping, 1 for not wrapping.

**Comment by sergeche** [comment]
You can map <kbd>Ctrl+Alt+Enter</kbd> to run Wrap With Abbreviation action when there’s selection:

```
{
        "keys": ["ctrl+alt+enter"],
        "command": "emmet_wrap_with_abbreviation",
        "context": [{
            "key": "selection_empty",
            "operand": false
        }]
}
```
