### ISSUE TITLE
Behaviour of Evaluate Math Expression unexpected in new version

### ISSUE THREAD

**Issue by alimony** [emmetio/sublime-text-plugin#81]
It seems like the behaviour of the "Evaluate Math Expression" command has changed in the new version so it no longer supports evaluating the current selection, but instead always evaluates the entire line (maybe up until the caret, I can't determine the exact behaviour).

**Comment by sergeche** [comment]
Fixed in v2.1.11

**Comment by adragin** [comment]
Thanks for the quick fixes!
