### ISSUE TITLE
CSS abbreviations not working after update

### ISSUE THREAD

**Issue by mylesduncanking** [emmetio/sublime-text-plugin#84]
Hi,

Before the update I was able to enter css shortcodes which would expand to a full command. Some examples are:

### Before update

fz12 **tab** font-size: 12px;
tac **tab** text-align: center;
curp **tab** cursor: pointer;

### After update

fz12 **tab** fz12 
tac **tab** text-anchor: 
curp **tab** curp 

Is it possible to downgrade to v1 for the time being?

**Comment by sergeche** [comment]
Please check if Emmet is properly updated. Restart ST then open ST console and check if there are errors

**Comment by fabioars** [comment]
Same issue here

**Comment by yurigoytacaz** [comment]
I'm having the same problem here.
tried restarting and also tried removing Emmet (and stylus, and stylus snippets) and reinstalling all of them and then restarting and nothing fixed the issue.

**Comment by sergeche** [comment]
Please post contents of ST console here

**Comment by yurigoytacaz** [comment]
startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/yuri/Library/Application Support/Sublime Text 3/Packages
state path: /Users/yuri/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/yuri/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "ZenCoding"]
pre session restore time: 0.842656
using gpu buffer for window
startup time: 1.02069
git: tracking working dir /Users/yuri/Sites/enova
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-numpy
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.plugin
reloading plugin Advanced CSV.csvplugin
reloading plugin ayu.activation
reloading plugin ayu.Icons
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin Ecmascript Syntax.commands
reloading plugin Emmet.main
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin LESS.less_completions
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Sass.sass_completions
reloading plugin SassBeautify.SassBeautify
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin String 2 Lower Hyphen.String2LowerHyphen
reloading plugin Stylus.Stylus
reloading plugin Timenow.Timenow
reloading plugin Babel.Babel
reloading plugin WakaTime.WakaTime
reloading plugin User.IncrementSelection
plugins loaded
[WakaTime] [INFO] Initializing WakaTime plugin v9.1.2
Package Control: No updated packages

**Comment by sergeche** [comment]
@yurigoytacaz You have issues in CSS or Stylus syntax? Does it work in CSS and HTML?

**Comment by yurigoytacaz** [comment]
@sergeche sorry, I forgot to mention that my problem is with Stylus. 
I just did some testing and find out that it seems as if I need to enter abbreviation mode to get the expected output, for example: m10 should output margin 10 (in stylus). if I type m10 and hit tab, nothing happens, but if I enter abbreviation mode and then type m10, I get margin 10 as expected.
before entering abbreviation mode, if I type ttu I'll get transition-timing-function value, but if I enter abbrev. mode, I'll get what I expect, which is text-transform uppercase.
checked my emmet setting and it has "auto_mark": true and "abbreviation_preview": true by default and they are not disabled (false) in the user setting, so I dont know what I can do to make abbreviation mode to "always run". can you help me out?

**Comment by sergeche** [comment]
@yurigoytacaz you need proper selector in `abbreviation_scopes` Emmet preference: this setting is responsible for activation abbreviation when you type. You can run Show Scope command, it should be something like `source.stylus`. I'm AFK now, will check it by myself a bit later

**Comment by yurigoytacaz** [comment]
@sergeche nice!
just added source.stylus and it worked (= thank you, sir!

    "abbreviation_scopes": [
        "(text.html | text.xml) - source - meta - comment",
        "source.stylus - meta.property-value - meta.property-name - string - punctuation - comment",
        "(source.css | source.stylus | source.scss | source.less | source.postcss) & meta.property-list",
        "(source.css | source.stylus | source.scss | source.less | source.postcss) - meta.property-value - meta.property-name - string - comment",
        "(source.tsx | source.js | source.jsx) - comment",
