### ISSUE TITLE
Cannot expand HTML abbreviation in PHP tags

### ISSUE THREAD

**Issue by brodenbrett** [emmetio/sublime-text-plugin#85]
Hello,

Before the update I could expand HTML tag abbreviations within PHP strings, and now I am unable to do so.  Has this been discontinued, and if so is it possible to downgrade to v1?

**Comment by soysoluble** [comment]
Hi! I have the same issue.

I try change syntax_scopes on Emmet.sublime.settings but not works :(

     "syntax_scopes": {
		"html": "text.html - source - meta.attribute-with-value.style",
		"xml": "text.xml - text.xml.xsl",
		"xsl": "text.xml.xsl",
		"jsx": "source.js.jsx | source.tsx | source.js | source.jsx",
		"haml": "source.haml",
		"jade": "text.jade | source.pyjade",
		"pug": "text.pug | source.pypug",
		"slim": "text.slim",
		"php": "embedding.php text.html.basic",

		"css": "source.css | source.postcss | meta.attribute-with-value.style.html string.quoted",
		"sass": "source.sass",
		"scss": "source.scss",
		"less": "source.less",
		"stylus": "source.stylus",
		"sss": "source.sss"
	}

**Comment by sergeche** [comment]
You should change `abbreviation_scopes` property: it detects where abbreviation can be activated

**Comment by soysoluble** [comment]
> 
> 
> You should change `abbreviation_scopes` property: it detects where abbreviation can be activated

Thank you. This is the solution: https://github.com/emmetio/sublime-text-plugin/issues/50#issuecomment-679365586

**Comment by soysoluble** [comment]
> 
> 
> Hello,
> 
> Before the update I could expand HTML tag abbreviations within PHP strings, and now I am unable to do so. Has this been discontinued, and if so is it possible to downgrade to v1?

Hi! I resolve this copy / paste on key bindings user this code: https://github.com/emmetio/sublime-text-plugin/issues/50#issuecomment-679365586

**Comment by brodenbrett** [comment]
@soysoluble Hi, I tried putting this in my user key bindings, but it didn't seem to work for me.  Trying to expand an abbreviation inside PHP strings still isn't working.  For example:

```php
<?php 
'div.foo';  // My string

'<div class="foo"></div>'; // What it should expand into

'div.foo	' // What it is doing instead
?>
```

@sergeche Could you elaborate on how I can alter the `abbreviation_scopes` to achieve this?

**Comment by soysoluble** [comment]
@brodenbrett you're right. Try this:

echo '
div.foo
';

**Comment by sergeche** [comment]
Here’s a recipe for adding abbreviation capturing with interactive previews for PHP strings. You should open _Preferences > Package Settings > Emmet > Settings_:

1. Tell Emmet that PHP string literals are context for HTML syntax. In `syntax_scopes`, modify `html` selector as follows:

```json
"html": "text.html - source - meta.attribute-with-value.style, text.html source.php string",
```

2. Then tell Emmet that abbreviation should be captured as you type in PHP strings. Add the following selector into `abbreviation_scopes` property: `source.php string`

Save the file: now typing words in string literal will follow the same logic as in HTML.

I’ve also pushed v2.1.13, it improves logic of abbreviation extraction inside string literlas so you’ll be able to expand it right before quote, e.g. `'div.foo|'`.

**Comment by sergeche** [comment]
Also not that in [suggested solution](https://github.com/emmetio/sublime-text-plugin/issues/50#issuecomment-679365586) to mimic old Emmet behaviour with Tab key, you can limit `selector` argument to `source.php string` so it will work inside PHP string literals only

**Comment by soysoluble** [comment]
@sergeche thanks. Sorry for the question but not find documentation for add css auto prefix on this version :)

**Comment by brodenbrett** [comment]
@sergeche Thank you!  This solved my issue.  Appreciate the quick response and update as well
