### ISSUE TITLE
Emmet is missing

### ISSUE THREAD

**Issue by thewebprojects** [emmetio/sublime-text-plugin#86]
Hello, 

Emmet is missing from the Package Control https://packagecontrol.io/packages/Emmet

![ss](https://user-images.githubusercontent.com/19271269/91330250-2a102300-e797-11ea-8d89-94822fa74b29.jpg)

**Comment by sergeche** [comment]
It's a general issue with Package Control past few days, lots of packages are missing

**Comment by thewebprojects** [comment]
Got it. I'll wait impatiently until until they find it.  Thanks for your efforts on this great plugin/package.

**Comment by sergeche** [comment]
You can download it manually from https://emmetio.github.io/sublime-text-plugin/

**Comment by thewebprojects** [comment]
Excellent. I have it installed now. The reason I was trying to reinstalled was that I couldn't seem to increment numbers with the Cntrl + up arrow.  As if some recent update knocked that shortcut out.  Any insight?

**Comment by sergeche** [comment]
Yes, shortcuts are disabled by default because of complains, you should enable them manually: https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by thewebprojects** [comment]
Great. Thanks.
