### ISSUE TITLE
Lots of unnecessary fussing/alerts

### ISSUE THREAD

**Issue by thewebprojects** [emmetio/sublime-text-plugin#87]
Hello.  I'm getting lots of fussing from Emmet when typing out basic CSS.  This wasn't an issue before the update. 

![ss](https://user-images.githubusercontent.com/19271269/91342538-34d3b380-e7a9-11ea-81cb-4d9101782996.jpg)

Any insight? Maybe there's an option to disable this feature?

**Comment by sergeche** [comment]
Can you describe what you did to get this error? It's an abbreviation validator, should appear only when you edit abbreviation

**Comment by thewebprojects** [comment]
I created a quick video of when it happens.  It's just plain 'old css composing.  

http://somup.com/cYjOYc6Wvn

**Comment by sergeche** [comment]
Hmm, it looks like you’re using very old Emmet 2 version. How did you installed it? What version are you using?

**Comment by thewebprojects** [comment]
oh.  you sent me a link to manually install it earlier today.

**Comment by sergeche** [comment]
Oh, looks like my build system failed a bit 😬
Try this direct link: https://emmetio.github.io/sublime-text-plugin/2.1.12/Emmet.sublime-package

**Comment by thewebprojects** [comment]
lookin' good.  seems to be up and running as expected.
