### ISSUE TITLE
Add CSS Automatic prefixes

### ISSUE THREAD

**Issue by soysoluble** [emmetio/sublime-text-plugin#88]
How add Automatic prefixes? :(

**Comment by soysoluble** [comment]
I try with this https://docs.emmet.io/customization/preferences/ but not works

**Comment by sergeche** [comment]
Vendor prefixes are no longer supported, it's better to use PostCSS for this

**Comment by soysoluble** [comment]
@sergeche It's too sad, I don't know how to use the console and it wasn't too easy in the previous version. I think I will have to use the snippes. Thanks.

**Comment by ncorso** [comment]
Is there any way to emulate Emmet's V1 vendor prefixes with snippets?

**Comment by sergeche** [comment]
@ncorso You can create any snippet either using Emmet or native ST snippets
