### ISSUE TITLE
Add option to disable emmet for certain scopes

### ISSUE THREAD

**Issue by AmjadHD** [emmetio/sublime-text-plugin#9]
I want to disable emmet in markdown.

**Comment by sergeche** [comment]
Now you can add scopes where Emmet abbreviation capturing should be ignored:

```json
"emmet_ignore_scopes": [
  "text.html.markdown"
]
```

Available in most recent 0.1.5 version

**Comment by AmjadHD** [comment]
@sregeche, just a question how do i update to the latest master using Package Control ?

**Comment by sergeche** [comment]
If you added custom repository as described in https://github.com/emmetio/sublime-text-plugin#installation, it should be updated automatically on editor restart. Or you can try to run `Package Control: Upgrade/Overwrite All Packages`

**Comment by sergeche** [comment]
@poke how did you disabled Emmet for Markdown?

**Comment by poke** [comment]
I configured Markdown as an ignored scope with your snippet above:

```
"emmet_ignore_scopes": [
  "text.html.markdown"
]
```

This stopped the Emmet abbreviations from running for everything I type. But when I type e.g. `div`, this is still underlined and I can press tab to expand it to `<div></div>`.

**Comment by poke** [comment]
Oh, sorry, you’re right, I actually did go to the Emmet settings and added it as just `ignore_scopes`. I didn’t realize that I was looking at something different here. I think when I added the setting, I copied the name over from the default settings and just entered the scope name from what you wrote here.

Anyway, thanks for the super quick fix! The update apparently hasn’t made it to PackageControl yet but I’m looking forward to trying it out when it’s there.

**Comment by poke** [comment]
I just had the chance to test the update and the ignored scope now indeed prevents snippets from running in Markdown files. So yay, thanks for that!

Btw. I also tested removing the ignored scope again; for some reason the behavior is no longer that snippets and Emmet expansions are underlined. I’m not sure if this is actually related to this fix or maybe just a different side-effect now.

**Comment by sergeche** [comment]
In fixed version, Emmet uses both `abbreviation_scopes` and `ignore_scopes` to check if abbreviation should be captured at caret location. Maybe caret is outside of `abbreviation_scopes`

**Comment by poke** [comment]
Ah yes, that makes sense! When I add Markdown explicitly to the `abbreviation_scopes` it works again. Thanks for the clarification and thanks again for the quick fix! This helped a lot :blush:
