### ISSUE TITLE
Expansion of html attributes does not work

### ISSUE THREAD

**Issue by adragin** [emmetio/sublime-text-plugin#90]
Is there some way to create keyboard shortcuts for html attributes?
Like this:
type `h` + TAB => expand `height="{cursor}" `
type `cl` + TAB => expand `class="{cursor}" ` etc

**Comment by michaelalandawson** [comment]
You might be able to use Sublime Text snippets for this.  You might also be able to use Emmet snippets, as well.

**Comment by adragin** [comment]
In the previous version of Emmet it worked like this

**Comment by adragin** [comment]
@michaelalandawson 
I work with email and have some inconvenience after the update.
In the previous version of Emmet, it worked like this:
`"bg" : "bgcolor=\"#|\" ",` from html section of snippets.json worked inside the html-tag and expanded the attribute
`"bg" : "background:#|; "` from css section of snippets.json worked inside the css-inline style and expanded the css property  
Please advise how to be now?
@sergeche maybe you could suggest a solution?

**Comment by sergeche** [comment]
@adragin Yes, the best solution is to create native ST snippet with proper scope that points to tag context. For reference, you can open Preferences > Package Settings > Emmet > Key Bindings and check selector for `emmet_insert_attribute` action, which points to proper scope

**Comment by adragin** [comment]
@sergeche But is this command can be used to insert any attribute, not just a class and ID?

**Comment by sergeche** [comment]
Yes, you can basically bind any character to insert predefined command. But in your case, I would suggest to use native snippets
