### ISSUE TITLE
[CTRL + W] Wrap not working since update?

### ISSUE THREAD

**Issue by LucasTheillet** [emmetio/sublime-text-plugin#92]
Hello,

Being able to select a long HTML string, and Ctrl+W (on macOS) to wrap it into a new custom div was extremely useful, was it removed with the 2.0 version?

Thanks in advance

**Comment by soysoluble** [comment]
@LucasTheillet you can add this on key bindings user:

{
     "keys": ["shift+ctrl+g"],
     "command": "emmet_wrap_with_abbreviation",
     "context": [{"key": "setting.is_widget",  "operand": false }]
}

**Comment by LucasTheillet** [comment]
Yea I have it enabled but it does nothing at all.

**Comment by sergeche** [comment]
@LucasTheillet try to run Wrap With Abbreviation command from command palette. As noted above, shortcuts are not enabled by default
