### ISSUE TITLE
New format broke my snippets

### ISSUE THREAD

**Issue by CodeartistSerge** [emmetio/sublime-text-plugin#94]
With the recent update I got all of my snippets broken, literally none of them work.

I'm not sure if I've been abusing snippets system so far, because current doc says that now snippets are just shortcuts for abbreviations, but the way I use them was way beyond shortcuts.

For instance, in previous versions I could've toss something like that into the configs:
```
"snippets":
    {
        "cmz": "<?php echo \\$opt['${class}$1'];//comment_start\n\t\\$opt['${class}$1']='${child}';\n\t//comment_end?>",
        "cmzi": "<?php echo \\$opt['${class}$1']; ?>"
    }
```
and in HTML context simply select some text, wrap it with abbreviation like this `cmz.random_var_name` which then expanded into a nice piece of code like that:
```
<?php
    echo $opt['random_var_name'];//comment_start
    $opt['random_var_name']='selected text';
    //comment_end
?>
```
Now it only allows me to use something like this in the snippet section ignoring everything which is not Emmet abbreviations:
```
"snippets":
    {
        "foo": "foo.bar>baz"
    }
```

Although, it's per docs I am still a bit disappointed because it was working perfectly for years with previous versions & now it's just broken. Is there any way to expand snippets beyond simple "shortcuts" to the abbreviations or at least have a way to fall back to the previous Emmet version until majority of the bugs are fixed & it will be more stable?

By the way, thanx a lot for your hard work and effort, Emmet has been my number one tool for so many years! I really appreciate the efforts.

**Comment by sergeche** [comment]
You should wrap arbitrary content with `{}` to act like a text node in terms of Emmet abbreviation, e.g. `{<?php ...}`.

Also, it's better to use creat snippets as native ST snippets, Emmet works much better with them now
