### ISSUE TITLE
Last update breaks twig conditions

### ISSUE THREAD

**Issue by or3lie** [emmetio/sublime-text-plugin#95]
Hello,

I noticed that the last update breaks my twig conditions.

For exemple if I want to write a twig condition like that :
`{% if someCondition.something %}{% endif %}`
when I type the point my condition becomes
`{% if someCondition class="" %}{% endif %}`

So I can't write my twig conditions anymore :(

Thanks for your help

**Comment by sergeche** [comment]
Duplicate of https://github.com/emmetio/sublime-text-plugin/issues/91
