### ISSUE TITLE
Incorrect unfolding contraction

### ISSUE THREAD

**Issue by adragin** [emmetio/sublime-text-plugin#96]
Incorrect unfolding contraction:

expectation:
`<td style="bg#f8" >` -> `<td style="background:#f8f8f8;">`

reality:
`<td style="bg#f1" >` -> `<td style="background:#f0f0f0;">`
`<td style="bg#f2" >` -> `<td style="background:#f0f0f0;">`
`<td style="bg#f3" >` -> `<td style="background:#f0f0f0;">`
`<td style="bg#f4" >` -> `<td style="background:#f0f0f0;">`
`<td style="bg#f5" >` -> `<td style="background:#f0f0f0;">`
`<td style="bg#f6" >` -> `<td style="background:#f0f0f0;">`

https://s3.amazonaws.com/tz9i2p4ymw/n1p78108b5154sv7e52.png

**Comment by sergeche** [comment]
Fixed in v2.1.16

**Comment by adragin** [comment]
Thanks!
