### ISSUE TITLE
Possible "Auto mark" bug

### ISSUE THREAD

**Issue by guimadaleno** [emmetio/sublime-text-plugin#99]
Hi @sergeche. 
Thank you for your effort on this amazing project and as well as your patience with the community.

I've been having some issues with the latest **2.1.16** as well. 
I'm still unsure if it's something with my ST3 settings or a possible Emmet bug.
So I just wanted to show, in practice, what's going on with my ST3. 

![Emmet bug](https://s8.gifyu.com/images/Emmet-Bugs.gif)

If that's a possible bug, hope this could help.

**Emmet.sublime-settings file:**

`{
	"telemetry": false,
	"uid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}`

**Tested in:**
_SublimeText 3.2.2 Build 3211
Emmet 2.1.16 with empty settings
Packages I'm using: Emmet, Hasher, Material Theme, Open Folder, Package Control, PyV8, Sublime Git_

**Comment by sergeche** [comment]
Unable to reproduce it in recent version, does this issue still relevant?
